import { Link } from 'react-router-dom'
import { ArticleQualityIndicator, EditorialStatusBadge } from '@/components/article/ArticleComponents'
import { medicalArticles } from '@/content/articles'
import { isReviewOverdue, validateArticle } from '@/utils/contentValidation'

export function EditorialDashboardPage(){
  const stats=[['Total artikel',medicalArticles.length],['Draft',medicalArticles.filter(a=>a.status==='draft').length],['Dalam review',medicalArticles.filter(a=>a.status==='in_review').length],['Perlu revisi',medicalArticles.filter(a=>a.status==='revision_required').length],['Published',medicalArticles.filter(a=>a.status==='published').length],['Tinjauan lewat jadwal',medicalArticles.filter(a=>isReviewOverdue(a)).length],['Tanpa referensi',medicalArticles.filter(a=>!a.references.length).length],['Tanpa reviewer',medicalArticles.filter(a=>!a.medicalReviewerId).length],['Tanpa deskripsi SEO',medicalArticles.filter(a=>!a.seo.description).length]]
  return <div className='editorial-page'><header className='editorial-header'><div><span>INTERNAL · CONTENT HEALTH</span><h1>Editorial Lentera</h1><p>Ringkasan deterministik untuk kesiapan publikasi dan tanggung jawab pembaruan.</p></div><Link to='/'>Lihat situs publik</Link></header><main><section className='editorial-stats' aria-label='Ringkasan konten'>{stats.map(([label,value])=><article key={label}><strong>{value}</strong><span>{label}</span></article>)}</section><section className='editorial-table-wrap'><header><div><span>CONTENT INVENTORY</span><h2>Semua artikel</h2></div><p>Pemeriksaan ini bukan review berbasis AI.</p></header><div className='editorial-table-scroll'><table><thead><tr><th scope='col'>Artikel</th><th scope='col'>Status</th><th scope='col'>Kualitas</th><th scope='col'>Diperbarui</th><th scope='col'>Aksi</th></tr></thead><tbody>{medicalArticles.map(article=><tr key={article.id}><td><strong>{article.title}</strong><small>{article.slug}</small></td><td><EditorialStatusBadge status={article.status}/></td><td><ArticleQualityIndicator result={validateArticle(article,medicalArticles)}/></td><td>{article.updatedAt}</td><td><Link to={`/editorial/articles/${article.id}`}>Periksa</Link></td></tr>)}</tbody></table></div></section></main></div>
}
