import { AlertTriangle, Bookmark, CalendarClock, CheckCircle2, Clock3, ExternalLink, UserRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { authors } from '@/content/authors'
import { categoryById } from '@/content/categories'
import { reviewers } from '@/content/reviewers'
import { isReviewOverdue } from '@/utils/contentValidation'
import type { ArticleBlock, ArticleStatus, MedicalArticle, ValidationResult } from '@/types/content'

const date = (value?:string) => value ? new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${value}T12:00:00`)) : 'Belum tersedia'
export function EditorialStatusBadge({status}:{status:ArticleStatus}) { const labels:Record<ArticleStatus,string>={draft:'Draft',in_review:'In Review',revision_required:'Revision Required',approved:'Approved',published:'Published',archived:'Archived'}; return <span className={`editorial-status status-${status}`}>{labels[status]}</span> }
export function ReviewFreshnessBadge({article}:{article:MedicalArticle}) { return isReviewOverdue(article) ? <p className='review-freshness overdue'><CalendarClock/> Konten ini perlu ditinjau kembali.</p> : article.nextReviewAt ? <p className='review-freshness'><CheckCircle2/> Tinjauan berikutnya {date(article.nextReviewAt)}</p> : null }
export function ReviewerMeta({article}:{article:MedicalArticle}) { const author=authors.find(item=>item.id===article.authorId); const reviewer=reviewers.find(item=>item.id===article.medicalReviewerId); return <dl className='reviewer-meta'><div><dt>Ditulis oleh</dt><dd><UserRound/>{author?.name ?? 'Tim Editorial Lentera'}</dd></div><div><dt>Ditinjau secara medis oleh</dt><dd>{reviewer ? `${reviewer.name}${reviewer.credentials?`, ${reviewer.credentials}`:''}` : 'Reviewer medis belum ditetapkan'}</dd></div><div><dt>Terakhir ditinjau</dt><dd>{date(article.lastReviewedAt)}</dd></div><div><dt>Pembaruan berikutnya</dt><dd>{date(article.nextReviewAt)}</dd></div></dl> }
export function ArticleMeta({article}:{article:MedicalArticle}) { return <div className='article-meta'><span>{categoryById(article.categoryId)?.title ?? 'Tanpa kategori'}</span><span><Clock3/> {article.readingTime ?? 5} menit baca</span><span>Diperbarui {date(article.updatedAt)}</span></div> }
export function ArticleHeader({article,preview=false}:{article:MedicalArticle;preview?:boolean}) { return <header className='medical-article-header'>{preview&&<strong className='preview-banner'>PREVIEW — Belum Dipublikasikan</strong>}<ArticleMeta article={article}/><h1>{article.title}</h1>{article.subtitle&&<p className='article-subtitle'>{article.subtitle}</p>}<p className='article-excerpt'>{article.excerpt}</p><ReviewerMeta article={article}/><ReviewFreshnessBadge article={article}/></header> }
export function KeyTakeaways({items}:{items:string[]}) { return <aside className='key-takeaways' aria-labelledby='takeaway-title'><h2 id='takeaway-title'>Yang perlu Anda ketahui</h2><ul>{items.slice(0,5).map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul></aside> }
export function MedicalWarning({text}:{text:string}) { return <aside className='medical-warning'><AlertTriangle/><div><strong>Perlu perhatian</strong><p>{text}</p></div></aside> }
export function ArticleTableOfContents({blocks}:{blocks:ArticleBlock[]}) { const headings=blocks.filter((block):block is Extract<ArticleBlock,{type:'heading'}>=>block.type==='heading'); if(headings.length<1)return null; return <details className='article-toc' open><summary>Daftar isi</summary><nav aria-label='Daftar isi artikel'><ol>{headings.map(block=><li key={block.id}><a href={`#${block.id}`}>{block.text}</a></li>)}</ol></nav></details> }
export function ArticleReferenceList({article}:{article:MedicalArticle}) { const labels={guideline:'Guideline',systematic_review:'Systematic Review',journal:'Peer-reviewed Journal',government:'Government',organization:'Professional Organization',textbook:'Textbook'}; return <section className='article-references' id='referensi'><h2>Referensi</h2>{article.references.length?<ol>{article.references.map(reference=><li key={reference.id}><span>{labels[reference.sourceType]}</span><p>{reference.authors&&`${reference.authors}. `}<cite>{reference.title}</cite>{reference.year&&`. ${reference.year}.`}</p>{reference.url&&<a href={reference.url} target='_blank' rel='noreferrer'>Buka sumber <ExternalLink/></a>}</li>)}</ol>:<p>Referensi perlu dilengkapi sebelum publikasi.</p>}</section> }
export function ArticleRevisionHistory({article}:{article:MedicalArticle}) { return <details className='revision-history'><summary>Riwayat Pembaruan</summary>{[...article.revisionHistory].sort((a,b)=>b.version-a.version).map(entry=><div key={`${entry.version}-${entry.date}`}><strong>Versi {entry.version}</strong><time dateTime={entry.date}>{date(entry.date)}</time><p>{entry.summary}</p>{entry.editor&&<small>{entry.editor}</small>}</div>)}</details> }
export function ArticleQualityIndicator({result}:{result:ValidationResult}) { const count=result.errors.length+result.warnings.length; return <div className={`quality-indicator ${result.errors.length?'has-errors':count?'has-warnings':'is-complete'}`}><strong>{result.errors.length?'Perlu diperbaiki':count?'Perlu dilengkapi':'Lengkap'}</strong><span>{result.errors.length} error · {result.warnings.length} peringatan</span></div> }
export function ArticleCard({article}:{article:MedicalArticle}) { return <article className='medical-article-card'>{article.featured&&<span className='featured-label'>Pilihan Lentera</span>}<p>{categoryById(article.categoryId)?.title}</p><h2><Link to={`/articles/${article.slug}`}>{article.title}</Link></h2><p>{article.excerpt}</p><footer><span><Clock3/> {article.readingTime ?? 5} menit</span><Link to={`/articles/${article.slug}`}>Baca artikel</Link></footer></article> }
export function ArticleBody({article}:{article:MedicalArticle}) { return <>{article.body.map(block=><Block key={block.id} block={block} article={article}/>)}</> }
function Block({block,article}:{block:ArticleBlock;article:MedicalArticle}) {
  if(block.type==='key_takeaway')return <KeyTakeaways items={block.items}/>
  if(block.type==='heading'){const H=block.level===2?'h2':'h3';return <H id={block.id}>{block.text}</H>}
  if(block.type==='paragraph')return <p>{block.text}</p>
  if(block.type==='bullet_list'||block.type==='numbered_list'){const List=block.type==='bullet_list'?'ul':'ol';return <List>{block.items.map(item=><li key={item}>{item}</li>)}</List>}
  if(block.type==='quote')return <blockquote>{block.text}{block.attribution&&<cite>{block.attribution}</cite>}</blockquote>
  if(block.type==='callout'||block.type==='evidence_note')return <aside className='evidence-note'><strong>{block.type==='callout'?(block.title??'Catatan'):'Catatan bukti'}</strong><p>{block.text}</p></aside>
  if(block.type==='medical_warning')return <MedicalWarning text={block.text}/>
  if(block.type==='image')return <figure><img src={block.src} alt={block.alt} loading='lazy'/>{block.caption&&<figcaption>{block.caption}</figcaption>}</figure>
  if(block.type==='table')return <div className='table-scroll'><table><caption>{block.caption}</caption><thead><tr>{block.headers.map(item=><th scope='col' key={item}>{item}</th>)}</tr></thead><tbody>{block.rows.map((row,index)=><tr key={index}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div>
  if(block.type==='faq')return <section><h2>Pertanyaan umum</h2>{block.items.map(item=><details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>
  if(block.type==='references')return <ArticleReferenceList article={article}/>
  if(block.type==='disclaimer')return <aside className='article-disclaimer'><strong>Catatan keselamatan</strong><p>{block.text}</p></aside>
  return null
}
