import { useMemo,useState,type FormEvent,type ReactNode } from 'react'
import { NavLink } from 'react-router-dom'
import { AlertTriangle,CalendarDays,CheckCircle2,ClipboardList,FileDiff,HeartPulse,Phone,Share2,ShieldCheck,Users } from 'lucide-react'
import { toast } from 'sonner'
import { usePatientApp } from './PatientAppContext'
import type { CaregiverTask,DocumentComparison,MedicationEntry,SafetyCheckIn,SymptomEntry } from './types/patientApp'

const uid=()=>crypto.randomUUID()
const isoToday=()=>new Date().toISOString().slice(0,10)
const formatDate=(date:string)=>new Intl.DateTimeFormat('id-ID',{dateStyle:'medium'}).format(new Date(`${date}T00:00:00`))
const severityValue:Record<SymptomEntry['severity'],number>={Ringan:1,Sedang:2,Berat:3}
function FeatureCard({children,className=''}:{children:ReactNode;className?:string}){return <section className={`p-card ${className}`}>{children}</section>}
function daysBetween(date:string,reference:string){return Math.floor((new Date(`${reference}T00:00:00`).getTime()-new Date(`${date}T00:00:00`).getTime())/86400000)}
async function shareText(title:string,text:string){try{if(navigator.share){await navigator.share({title,text});return}await navigator.clipboard.writeText(text);toast.success('Ringkasan disalin karena fitur berbagi tidak tersedia.')}catch(error){if((error as DOMException).name!=='AbortError')toast.error('Belum dapat membagikan ringkasan. Coba cetak sebagai alternatif.')}}

export function VisitSummary(){
  const {state,update}=usePatientApp()
  const upcoming=[...state.appointments].filter(x=>!x.completed).sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`))
  const [appointmentId,setAppointmentId]=useState(upcoming[0]?.id||state.appointments[0]?.id||'')
  const appointment=state.appointments.find(x=>x.id===appointmentId)
  const relevantSymptoms=state.symptoms.filter(x=>!appointment||Math.abs(daysBetween(x.date,appointment.date))<=14)
  const [included,setIncluded]=useState<Record<string,boolean>>({})
  const isIncluded=(key:string)=>included[key]!==false
  const toggle=(key:string)=>setIncluded(v=>({...v,[key]:!isIncluded(key)}))
  const checklist=state.checklists.flatMap(x=>x.items).filter(x=>!x.done)
  const lines=(items:{id:string;label:string}[])=>items.filter(x=>isIncluded(x.id)).map(x=>`• ${x.label}`).join('\n')||'-'
  const summary=`RINGKASAN KUNJUNGAN\n${appointment?`${appointment.type} — ${formatDate(appointment.date)}, ${appointment.time}\n${appointment.location}${appointment.clinician?` · ${appointment.clinician}`:''}`:'Jadwal belum dipilih'}\n\nPERTANYAAN BELUM TERJAWAB\n${lines(state.questions.filter(x=>!x.answered).map(x=>({id:`q-${x.id}`,label:x.text})))}\n\nGEJALA 14 HARI TERKAIT\n${lines(relevantSymptoms.map(x=>({id:`s-${x.id}`,label:`${x.symptom} (${x.severity}) — ${formatDate(x.date)}`})))}\n\nOBAT AKTIF\n${lines(state.medications.filter(x=>x.status!=='archived').map(x=>({id:`m-${x.id}`,label:`${x.name} — ${x.schedule}`})))}\n\nDOKUMEN DIBAWA\n${lines(state.documents.map(x=>({id:`d-${x.id}`,label:x.title})))}\n\nCHECKLIST BELUM SELESAI\n${lines(checklist.map(x=>({id:`c-${x.id}`,label:x.text})))}`
  const groups=[['Pertanyaan',state.questions.filter(x=>!x.answered).map(x=>({id:`q-${x.id}`,label:x.text}))],['Gejala 14 hari',relevantSymptoms.map(x=>({id:`s-${x.id}`,label:`${x.symptom} · ${x.severity}`}))],['Obat aktif',state.medications.filter(x=>x.status!=='archived').map(x=>({id:`m-${x.id}`,label:`${x.name} · ${x.schedule}`}))],['Dokumen dibawa',state.documents.map(x=>({id:`d-${x.id}`,label:x.title}))],['Checklist',checklist.map(x=>({id:`c-${x.id}`,label:x.text}))]] as const
  return <div className="feature-page visit-summary"><p className="lead">Pilih kunjungan, lalu tentukan informasi yang ingin dibawa. Semua diproses di perangkat ini.</p><FeatureCard><label>Kunjungan<select value={appointmentId} onChange={e=>setAppointmentId(e.target.value)}><option value="">Pilih jadwal</option>{state.appointments.map(x=><option key={x.id} value={x.id}>{formatDate(x.date)} · {x.type}</option>)}</select></label>{appointment&&<div className="appointment-banner"><CalendarDays/><div><b>{appointment.type}</b><span>{formatDate(appointment.date)} · {appointment.time}</span><span>{appointment.location}{appointment.clinician?` · ${appointment.clinician}`:''}</span></div></div>}</FeatureCard>{groups.map(([title,items])=><FeatureCard key={title}><div className="row"><h3>{title}</h3><small>{items.filter(x=>isIncluded(x.id)).length}/{items.length} dipilih</small></div>{items.length?items.map(item=><label className="check" key={item.id}><input type="checkbox" checked={isIncluded(item.id)} onChange={()=>toggle(item.id)}/><span>{item.label}</span></label>):<p>Belum ada data.</p>}</FeatureCard>)}<FeatureCard className="print-summary"><h2>Ringkasan siap dibawa</h2><pre>{summary}</pre></FeatureCard><div className="sticky-actions"><button className="primary" onClick={()=>shareText('Ringkasan Kunjungan',summary)}><Share2/> Bagikan</button><button onClick={()=>window.print()}>Cetak ringkasan</button></div><button className="sr-only" onClick={()=>update(s=>s)}>Simpan pilihan</button></div>
}

export function SymptomTrends(){
  const {state}=usePatientApp();const names=[...new Set(state.symptoms.map(x=>x.symptom))];const [filter,setFilter]=useState('Semua')
  const entries=useMemo(()=>state.symptoms.filter(x=>filter==='Semua'||x.symptom===filter).sort((a,b)=>a.date.localeCompare(b.date)).slice(-14),[state.symptoms,filter])
  const first=entries[0],last=entries[entries.length-1];const trend=!first||!last?'Belum cukup data':severityValue[last.severity]<severityValue[first.severity]?'Membaik':severityValue[last.severity]>severityValue[first.severity]?'Memburuk':'Stabil'
  const points=entries.map((x,i)=>`${entries.length===1?50:5+i*(90/(entries.length-1))},${90-severityValue[x.severity]*24}`).join(' ');const danger=entries.some(x=>x.severity==='Berat'&&['Demam','Sesak','Muntah'].includes(x.symptom))
  return <><div className="feature-hero"><HeartPulse/><div><small>POLA YANG TERCATAT</small><h2>{trend}</h2><p>Berdasarkan catatan yang Anda masukkan, bukan diagnosis.</p></div></div><label>Filter gejala<select value={filter} onChange={e=>setFilter(e.target.value)}><option>Semua</option>{names.map(x=><option key={x}>{x}</option>)}</select></label><FeatureCard><div className="chart-legend"><span>Berat</span><span>Sedang</span><span>Ringan</span></div>{entries.length?<svg className="symptom-chart" viewBox="0 0 100 100" role="img" aria-label={`Grafik ${entries.length} catatan gejala`}><path d="M5 18H95M5 42H95M5 66H95"/><polyline points={points}/>{entries.map((x,i)=><circle key={x.id} cx={entries.length===1?50:5+i*(90/(entries.length-1))} cy={90-severityValue[x.severity]*24} r="3"><title>{x.symptom}, {x.severity}, {formatDate(x.date)}</title></circle>)}</svg>:<p>Catat sedikitnya dua gejala untuk melihat pola.</p>}<div className="trend-list">{entries.map(x=><span key={x.id}><b>{x.symptom}</b><small>{formatDate(x.date)} · {x.severity}</small></span>)}</div></FeatureCard>{danger&&<div className="safety"><AlertTriangle/><div><b>Catatan perlu perhatian</b><p>Catatan berat tertentu ditemukan. Ini bukan pemantauan real-time.</p><NavLink to="/apps/red-flags">Buka petunjuk tanda bahaya</NavLink></div></div>}<NavLink className="primary link-button wide" to="/apps/visit-prep">Masukkan ke ringkasan kunjungan</NavLink></>
}

export function MedicationReview(){
  const {state,update}=usePatientApp();const [confirmations,setConfirmations]=useState<Record<string,string>>({})
  const setMedication=(item:MedicationEntry,patch:Partial<MedicationEntry>)=>update(s=>({...s,medications:s.medications.map(x=>x.id===item.id?{...x,...patch}:x)}))
  const report=`REKONSILIASI OBAT\n${state.medications.map(x=>`• ${x.name} | ${x.kind||'belum ditandai'} | ${x.schedule} | ${x.status}${x.scheduleChanged?' | JADWAL BERUBAH':''}${x.skippedReason?` | Alasan: ${x.skippedReason}`:''}`).join('\n')||'-'}\n\nHAL YANG PERLU DIKONFIRMASI\n${Object.values(confirmations).filter(Boolean).map(x=>`• ${x}`).join('\n')||'-'}`
  return <><p className="lead">Tinjau daftar ini bersama tenaga kesehatan. Lentera tidak memeriksa dosis atau interaksi obat.</p>{state.medications.map(m=><FeatureCard key={m.id}><div className="row"><div><h3>{m.name}</h3><p>{m.schedule} · {m.time}</p></div><span className={`status-badge ${m.status}`}>{m.status}</span></div><label>Jenis<select value={m.kind||''} onChange={e=>setMedication(m,{kind:e.target.value as MedicationEntry['kind']})}><option value="">Pilih jenis</option><option value="resep">Obat resep</option><option value="nonresep">Obat nonresep</option><option value="suplemen">Suplemen</option></select></label><label className="check"><input type="checkbox" checked={!!m.scheduleChanged} onChange={e=>setMedication(m,{scheduleChanged:e.target.checked})}/><span>Dosis atau jadwal berubah</span></label>{m.status==='skipped'&&<label>Alasan dilewati<input value={m.skippedReason||''} onChange={e=>setMedication(m,{skippedReason:e.target.value})}/></label>}<label>Hal yang perlu dikonfirmasi<input placeholder="Contoh: apakah tetap diminum sebelum terapi?" value={confirmations[m.id]||''} onChange={e=>setConfirmations(v=>({...v,[m.id]:e.target.value}))}/></label></FeatureCard>)}{!state.medications.length&&<FeatureCard><p>Belum ada obat. Tambahkan dahulu pada menu Obat.</p></FeatureCard>}<FeatureCard className="print-summary"><pre>{report}</pre></FeatureCard><div className="sticky-actions"><button className="primary" onClick={()=>shareText('Rekonsiliasi Obat',report)}>Bagikan</button><button onClick={()=>window.print()}>Cetak satu halaman</button></div></>
}

export function DocumentCompare(){
  const {state,update}=usePatientApp();const [older,setOlder]=useState(''),[newer,setNewer]=useState(''),[changes,setChanges]=useState(''),[question,setQuestion]=useState(''),[followUp,setFollowUp]=useState('')
  function save(e:FormEvent){e.preventDefault();const item:DocumentComparison={id:uid(),olderDocumentId:older,newerDocumentId:newer,changes,question,linkedFollowUpId:followUp||undefined,createdAt:new Date().toISOString()};update(s=>({...s,documentComparisons:[item,...s.documentComparisons],questions:question?[...s.questions,{id:uid(),text:question,category:'Perbandingan hasil'}]:s.questions}));toast.success('Perbandingan dan pertanyaan disimpan.');setChanges('');setQuestion('')}
  const meta=(docId:string)=>state.documents.find(x=>x.id===docId)
  return <><div className="safety"><FileDiff/><div><b>Bandingkan secara manual</b><p>Lentera tidak membaca atau menafsirkan isi hasil pemeriksaan.</p></div></div><form onSubmit={save}><div className="compare-grid"><FeatureCard><label>Hasil lama<select required value={older} onChange={e=>setOlder(e.target.value)}><option value="">Pilih dokumen</option>{state.documents.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>{meta(older)&&<p>{meta(older)?.category}<br/>{formatDate(meta(older)!.date)}<br/>{meta(older)?.filename}</p>}</FeatureCard><FeatureCard><label>Hasil terbaru<select required value={newer} onChange={e=>setNewer(e.target.value)}><option value="">Pilih dokumen</option>{state.documents.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>{meta(newer)&&<p>{meta(newer)?.category}<br/>{formatDate(meta(newer)!.date)}<br/>{meta(newer)?.filename}</p>}</FeatureCard></div><FeatureCard><label>Perubahan angka atau istilah<textarea required value={changes} onChange={e=>setChanges(e.target.value)} placeholder="Salin atau tulis perubahan yang Anda lihat…"/></label><label>Pertanyaan untuk dokter<textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Apa arti perubahan ini untuk rencana saya?"/></label><label>Tautkan ke follow-up<select value={followUp} onChange={e=>setFollowUp(e.target.value)}><option value="">Tidak ditautkan</option>{state.followUps.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><button className="primary wide" disabled={!state.documents.length}>Simpan perbandingan</button></FeatureCard></form>{state.documentComparisons.map(x=><FeatureCard key={x.id}><small>PERBANDINGAN TERSIMPAN</small><h3>{meta(x.olderDocumentId)?.title||'Dokumen lama'} → {meta(x.newerDocumentId)?.title||'Dokumen terbaru'}</h3><p>{x.changes}</p>{x.question&&<b>Pertanyaan: {x.question}</b>}</FeatureCard>)}</>
}

export function CaregiverHandoff(){
  const {state,update}=usePatientApp();const [open,setOpen]=useState(false)
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const task:CaregiverTask={id:uid(),title:String(f.get('title')),assignee:String(f.get('assignee')),status:'perlu-dibantu',comment:String(f.get('comment')),expiresAt:String(f.get('expiresAt')),permissions:f.getAll('permissions') as CaregiverTask['permissions'],revoked:false,activity:[`Akses dibuat ${new Date().toLocaleString('id-ID')}`]};update(s=>({...s,caregiverTasks:[task,...s.caregiverTasks]}));setOpen(false);toast.success('Tugas pendamping dibuat di perangkat ini.')}
  const patch=(task:CaregiverTask,data:Partial<CaregiverTask>,activity:string)=>update(s=>({...s,caregiverTasks:s.caregiverTasks.map(x=>x.id===task.id?{...x,...data,activity:[activity,...x.activity]}:x)}))
  return <><div className="safety"><ShieldCheck/><div><b>Kontrol ada pada pasien</b><p>Bagikan hanya informasi yang diperlukan dan cabut akses kapan saja.</p></div></div>{state.caregiverTasks.map(task=><FeatureCard key={task.id} className={task.revoked?'revoked':''}><div className="row"><div><small>{task.revoked?'AKSES DICABUT':task.status.replace('-',' ').toUpperCase()}</small><h3>{task.title}</h3><p>{task.assignee} · berlaku sampai {formatDate(task.expiresAt)}</p></div><Users/></div><div className="chips">{task.permissions.map(x=><span key={x}>{x}</span>)}</div><label>Status<select disabled={task.revoked} value={task.status} onChange={e=>patch(task,{status:e.target.value as CaregiverTask['status']},`Status diubah menjadi ${e.target.value}`)}><option value="perlu-dibantu">Perlu dibantu</option><option value="dikerjakan">Sedang dikerjakan</option><option value="selesai">Selesai</option></select></label><label>Komentar singkat<textarea disabled={task.revoked} value={task.comment} onChange={e=>patch(task,{comment:e.target.value},'Komentar diperbarui')}/></label><details><summary>Log aktivitas ({task.activity.length})</summary><ul>{task.activity.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul></details>{!task.revoked&&<button className="danger" onClick={()=>patch(task,{revoked:true},`Akses dicabut ${new Date().toLocaleString('id-ID')}`)}>Cabut akses</button>}</FeatureCard>)}<button className="primary wide" onClick={()=>setOpen(!open)}>+ Beri tugas terbatas</button>{open&&<FeatureCard><form className="p-form" onSubmit={submit}><label>Tugas<input name="title" required/></label><label>Nama pendamping<input name="assignee" required/></label><label>Berlaku sampai<input type="date" name="expiresAt" min={isoToday()} required/></label><fieldset><legend>Informasi yang boleh dilihat</legend>{[['schedule','Jadwal'],['checklist','Checklist'],['documents','Dokumen'],['questions','Pertanyaan']].map(([v,l])=><label className="check" key={v}><input type="checkbox" name="permissions" value={v}/><span>{l}</span></label>)}</fieldset><label>Catatan singkat<textarea name="comment"/></label><button className="primary">Buat handoff</button></form></FeatureCard>}</>
}

export function TherapyDay(){
  const {state}=usePatientApp();const candidate=[...state.appointments].filter(x=>x.date>=isoToday()&&!x.completed).sort((a,b)=>a.date.localeCompare(b.date))[0];const checklist=state.checklists.find(x=>x.category.toLowerCase().includes(candidate?.type.toLowerCase()||'terapi'))||state.checklists[0]
  return <div className="therapy-mode"><div className="feature-hero"><CalendarDays/><div><small>{candidate?.date===isoToday()?'AGENDA HARI INI':'AGENDA BERIKUTNYA'}</small><h1>{candidate?.type||'Belum ada agenda'}</h1><p>{candidate?`${formatDate(candidate.date)} · ${candidate.time}`:'Tambahkan jadwal untuk memulai.'}</p></div></div>{candidate&&<><FeatureCard><h2>{candidate.location}</h2>{candidate.clinician&&<p>Tujuan: {candidate.clinician}</p>}{candidate.contact&&<a className="primary link-button wide" href={`tel:${candidate.contact}`}><Phone/> Hubungi fasilitas</a>}</FeatureCard><FeatureCard><h2>Yang perlu dibawa</h2>{checklist?.items.map(x=><label className="check" key={x.id}><input type="checkbox" readOnly checked={x.done}/><span>{x.text}</span></label>)}{state.documents.slice(0,3).map(x=><p key={x.id}>📄 {x.title}</p>)}</FeatureCard><FeatureCard><h2>Obat & instruksi tercatat</h2>{state.medications.filter(x=>x.status!=='archived').map(x=><p key={x.id}><b>{x.name}</b><br/>{x.schedule} · {x.status}</p>)}</FeatureCard><NavLink className="therapy-action" to="/apps/diary"><HeartPulse/>Catat kondisi saya</NavLink></>}<p className="disclaimer">Mode ini dapat dibuka dari data lokal saat aplikasi tersedia. Informasi bukan instruksi medis resmi.</p></div>
}

export function SafetyCheckInPage(){
  const {state,update}=usePatientApp();const [latest,setLatest]=useState<SafetyCheckIn>()
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const item:SafetyCheckIn={id:uid(),date:isoToday(),wellbeing:f.get('wellbeing') as SafetyCheckIn['wellbeing'],symptoms:f.getAll('symptoms') as string[],severity:f.get('severity') as SafetyCheckIn['severity'],hydration:f.get('hydration') as SafetyCheckIn['hydration'],activity:f.get('activity') as SafetyCheckIn['activity'],note:String(f.get('note'))};update(s=>({...s,safetyCheckIns:[item,...s.safetyCheckIns]}));setLatest(item);toast.success('Check-in tersimpan lokal.')}
  const urgent=latest&&(latest.severity==='Berat'||latest.hydration==='Sulit'||latest.activity==='Tidak mampu'||latest.symptoms.some(x=>['Sesak','Demam','Perdarahan'].includes(x)))
  return <><div className="safety"><AlertTriangle/><div><b>Respons tidak dipantau tenaga kesehatan</b><p>Jika merasa dalam kondisi darurat, hubungi fasilitas atau layanan gawat darurat setempat sekarang.</p></div></div><FeatureCard><form className="p-form" onSubmit={submit}><label>Bagaimana kondisi Anda hari ini?<select name="wellbeing" required><option>Baik</option><option>Cukup</option><option>Buruk</option></select></label><fieldset><legend>Gejala yang dicatat</legend>{['Mual','Muntah','Nyeri','Demam','Sesak','Perdarahan','Lelah'].map(x=><label className="check" key={x}><input type="checkbox" name="symptoms" value={x}/><span>{x}</span></label>)}</fieldset><label>Keparahan tertinggi<select name="severity"><option>Ringan</option><option>Sedang</option><option>Berat</option></select></label><label>Makan/minum<select name="hydration"><option>Baik</option><option>Sulit</option></select></label><label>Aktivitas<select name="activity"><option>Normal</option><option>Terbatas</option><option>Tidak mampu</option></select></label><label>Catatan<textarea name="note"/></label><button className="primary">Simpan check-in</button></form></FeatureCard>{latest&&<div className={urgent?'urgent-result':'safe-result'}>{urgent?<><AlertTriangle/><div><h2>Cari bantuan sekarang</h2><p>Catatan Anda memenuhi aturan eskalasi keselamatan. Hubungi tim perawatan atau layanan gawat darurat setempat. Jangan menunggu respons dari aplikasi.</p><NavLink to="/apps/red-flags">Buka petunjuk darurat</NavLink></div></>:<><CheckCircle2/><div><h2>Check-in tersimpan</h2><p>Tetap ikuti instruksi khusus dari tim perawatan dan catat bila kondisi berubah.</p></div></>}</div>}<h2>Riwayat check-in</h2>{state.safetyCheckIns.slice(0,5).map(x=><FeatureCard key={x.id}><div className="row"><b>{formatDate(x.date)}</b><span>{x.wellbeing} · {x.severity}</span></div></FeatureCard>)}</>
}

export function CareLoadMap(){
  const {state}=usePatientApp()
  const events=[
    ...state.appointments.map(x=>({id:`a-${x.id}`,date:x.date,title:x.type,type:'Janji temu',done:x.completed})),
    ...state.followUps.flatMap(x=>x.tasks.map((task,i)=>({id:`f-${x.id}-${i}`,date:x.date,title:task,type:'Tugas follow-up',done:x.history}))),
    ...state.medications.filter(x=>x.status==='pending').map(x=>({id:`m-${x.id}`,date:isoToday(),title:`Ambil/konfirmasi ${x.name}`,type:'Obat',done:false})),
  ]
  const grouped=events.reduce<Record<string,typeof events>>((result,event)=>({...result,[event.date]:[...(result[event.date]||[]),event]}),{})
  const dates=Object.keys(grouped).sort()
  return <><p className="lead">Gabungan agenda dan tugas yang Anda catat. Lentera tidak mengubah jadwal fasilitas.</p>{dates.map(date=>{const day=grouped[date],busy=day.length>=3;return <FeatureCard key={date} className={busy?'busy-day':''}><div className="row"><div><small>{busy?'HARI PADAT — PERLU DIKONFIRMASI':'BEBAN TERJADWAL'}</small><h2>{formatDate(date)}</h2></div><b>{day.length} item</b></div>{day.map(x=><div className="load-item" key={x.id}><span className={x.done?'done':''}/><div><b>{x.title}</b><small>{x.type}{x.done?' · selesai':''}</small></div></div>)}{busy&&<p className="load-warning">Beberapa kebutuhan tercatat pada hari yang sama. Konfirmasi waktu, transportasi, dan bantuan pendamping.</p>}</FeatureCard>})}{!dates.length&&<FeatureCard><ClipboardList/><p>Belum ada beban perawatan untuk dipetakan.</p></FeatureCard>}</>
}
