import { useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { Check, ClipboardList, Copy, FileText, Plus, Printer, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { followUpRepository } from '@/services/followUpRepository'
import { followUpSummary } from '@/services/followUpSummaryService'
import type { FollowUpData, FollowUpPlan, FollowUpTask, FollowUpTaskType, FollowUpVisit } from '@/types/followUp'
import type { MedicationSchedule, SymptomEntry } from '@/types/companion'

export const defaultFollowUpChecklist=['Catat keluhan atau perubahan baru','Siapkan daftar obat','Siapkan hasil pemeriksaan terbaru','Catat pertanyaan','Konfirmasi waktu kontrol','Siapkan dokumen yang dibutuhkan']
const format=(date?:string)=>date?new Date(`${date}T00:00`).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'}):'Tanggal belum dicatat'
export function NextFollowUpCard({plan,data}:{plan?:FollowUpPlan;data:FollowUpData}){if(!plan)return <section className='fu-card fu-next'><span>KONTROL BERIKUTNYA</span><h2>Belum ada jadwal follow-up yang Anda catat.</h2><Link className='fu-button primary' to='/follow-up/new'>Tambah Rencana</Link></section>;const done=plan.checklist.filter(x=>x.done).length,q=data.questions.filter(x=>!x.planId||x.planId===plan.id).length;return <section className='fu-card fu-next'><span>KONTROL BERIKUTNYA</span><time dateTime={plan.nextFollowUpDate}>{format(plan.nextFollowUpDate)}</time><h2>{plan.title}</h2>{plan.facility&&<p>{plan.facility}</p>}<dl><div><dt>Persiapan</dt><dd>{done}/{plan.checklist.length} selesai</dd></div><div><dt>Pertanyaan</dt><dd>{q} tersimpan</dd></div><div><dt>Dokumen</dt><dd>{plan.linkedDocumentIds.length} disiapkan</dd></div></dl><Link className='fu-button primary' to={`/follow-up/${plan.id}`}>Siapkan Follow-up</Link></section>}
export function FollowUpPlanCard({plan,data}:{plan:FollowUpPlan;data:FollowUpData}){const open=data.tasks.filter(x=>x.planId===plan.id&&!['completed','cancelled'].includes(x.status)).length;return <article className='fu-card plan-card'><span className='fu-status'>Status: {plan.status==='active'?'Aktif':plan.status==='paused'?'Dijeda':'Selesai'}</span><h3>{plan.title}</h3><p>{plan.nextFollowUpDate?`Berikutnya ${format(plan.nextFollowUpDate)}`:'Jadwal berikutnya belum dicatat'}</p>{plan.intervalText&&<small>{plan.intervalText}</small>}<footer><span>{open} tugas terbuka</span><Link to={`/follow-up/${plan.id}`}>Buka rencana</Link></footer></article>}
export function FollowUpChecklist({plan}:{plan:FollowUpPlan}){const [custom,setCustom]=useState('');const save=(checklist:FollowUpPlan['checklist'])=>followUpRepository.savePlan({...plan,checklist,updatedAt:new Date().toISOString()});return <section className='fu-card'><h2>Checklist persiapan</h2><p>{plan.checklist.filter(x=>x.done).length} dari {plan.checklist.length} selesai</p><progress max={plan.checklist.length||1} value={plan.checklist.filter(x=>x.done).length}/><div className='fu-checks'>{plan.checklist.map(x=><label className={x.done?'done':''} key={x.id}><input type='checkbox' checked={x.done} onChange={()=>save(plan.checklist.map(i=>i.id===x.id?{...i,done:!i.done}:i))}/><span><Check/></span>{x.label}</label>)}</div><div className='fu-inline'><input aria-label='Tugas persiapan khusus' value={custom} onChange={e=>setCustom(e.target.value)} placeholder='Tambah tugas sendiri'/><button onClick={()=>{if(!custom.trim())return;save([...plan.checklist,{id:crypto.randomUUID(),label:custom.trim(),done:false,custom:true}]);setCustom('')}}><Plus/> Tambah</button></div></section>}
const groups:Record<string,string[]>={'Tentang Kondisi Saat Ini':['Apa yang perlu saya pantau setelah terapi?','Keluhan apa yang penting untuk saya laporkan?'],'Tentang Follow-up':['Kapan kontrol berikutnya?','Pemeriksaan apa yang direncanakan?','Apa tujuan pemeriksaan tersebut?'],'Tentang Aktivitas':['Apakah ada batasan aktivitas?','Kapan saya dapat kembali ke aktivitas biasa?'],'Tentang Efek Jangka Panjang':['Efek terapi apa yang dapat muncul kemudian?','Apa yang perlu dipantau dalam jangka panjang?']}
export function FollowUpQuestionBuilder({planId,data}:{planId:string;data:FollowUpData}){const [draft,setDraft]=useState('');const add=(text:string,category:string)=>{if(data.questions.some(x=>x.planId===planId&&x.text===text))return;followUpRepository.saveQuestion({id:crypto.randomUUID(),planId,text,category,answered:false,createdAt:new Date().toISOString()})};const own=data.questions.filter(x=>x.planId===planId);return <section className='fu-card'><h2>Pertanyaan untuk kontrol</h2>{Object.entries(groups).map(([category,items])=><details key={category}><summary>{category}</summary>{items.map(text=><button className='fu-suggestion' key={text} onClick={()=>add(text,category)}><Plus/> {text}</button>)}</details>)}<div className='fu-inline'><input aria-label='Pertanyaan khusus' value={draft} onChange={e=>setDraft(e.target.value)} placeholder='Tulis pertanyaan sendiri'/><button onClick={()=>{if(draft.trim()){add(draft.trim(),'Pertanyaan Saya');setDraft('')}}}>Tambah</button></div>{own.length?<ul className='question-list'>{own.map(q=><li key={q.id}><label><input type='checkbox' checked={q.answered} onChange={()=>followUpRepository.saveQuestion({...q,answered:!q.answered})}/>{q.text}</label><button aria-label={`Hapus pertanyaan ${q.text}`} onClick={()=>followUpRepository.deleteQuestion(q.id)}><Trash2/></button></li>)}</ul>:<p>Belum ada pertanyaan tersimpan.</p>}</section>}
export function OutstandingFollowUpItems({tasks}:{tasks:FollowUpTask[]}){const open=tasks.filter(x=>!['completed','cancelled'].includes(x.status));return <section className='fu-card'><h2>Yang masih perlu diselesaikan</h2>{open.length?<ul>{open.map(x=><li key={x.id}><ClipboardList/> <span><strong>{x.title}</strong>{x.plannedDate&&<small>{format(x.plannedDate)}</small>}</span></li>)}</ul>:<p>Semua tugas yang dicatat sudah selesai atau belum ada tugas.</p>}</section>}
export function FollowUpTimeline({data,query=''}:{data:FollowUpData;query?:string}){const entries=[...data.tasks.map(x=>({id:x.id,date:x.plannedDate||x.createdAt.slice(0,10),title:x.title,status:x.status==='completed'?'Selesai':x.status==='cancelled'?'Dibatalkan':'Mendatang',type:x.type,facility:''})),...data.visits.map(x=>({id:x.id,date:x.date,title:'Catatan kontrol',status:'Selesai',type:'Konsultasi',facility:x.facility||''}))].filter(x=>`${x.title} ${x.type} ${x.facility}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));return entries.length?<ol className='fu-timeline' aria-label='Riwayat follow-up'>{entries.map(x=><li key={`${x.id}-${x.title}`}><time dateTime={x.date}>{format(x.date)}</time><div><strong>{x.title}</strong><small>{x.type}{x.facility&&` · ${x.facility}`}</small><span>Status: {x.status}</span></div></li>)}</ol>:<p className='fu-empty'>Belum ada riwayat yang cocok. Linimasa hanya menampilkan informasi yang Anda masukkan.</p>}
export function FollowUpVisitForm({planId,onDone}:{planId:string;onDone:()=>void}){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const get=(x:string)=>String(d.get(x)||'');const visit:FollowUpVisit={id:crypto.randomUUID(),planId,date:get('date'),facility:get('facility'),clinician:get('clinician'),discussionNotes:get('discussion'),unclearNotes:get('unclear'),nextSteps:get('nextSteps'),requestedTests:get('tests'),medicationsDiscussed:get('medications'),questionsAnswered:get('answered'),unansweredQuestions:get('unanswered'),weightNote:get('weight'),symptomNotes:get('symptoms'),medicationList:get('medicationList'),appointmentNotes:get('appointments'),nextFollowUpDate:get('nextDate'),createdAt:new Date().toISOString()};followUpRepository.saveVisit(visit);toast.success('Catatan kontrol tersimpan');onDone()};return <form className='fu-form fu-card' onSubmit={submit}><h2>Catatan Kontrol</h2><div className='fu-form-grid'><label>Tanggal kunjungan<input name='date' type='date' required/></label><label>Fasilitas <small>opsional</small><input name='facility'/></label><label>Dokter <small>opsional</small><input name='clinician'/></label><label>Jadwal berikutnya <small>opsional</small><input name='nextDate' type='date'/></label>{[['discussion','Yang dibahas'],['unclear','Hal yang masih belum jelas'],['nextSteps','Tindakan berikutnya'],['tests','Pemeriksaan yang diminta'],['medications','Obat yang dibahas'],['answered','Pertanyaan terjawab'],['unanswered','Pertanyaan belum terjawab'],['weight','Catatan berat badan'],['symptoms','Catatan gejala'],['medicationList','Daftar obat'],['appointments','Catatan janji temu']].map(([name,label])=><label key={name}>{label}<textarea name={name}/></label>)}</div><button className='fu-button primary'>Simpan Catatan Kontrol</button></form>}
export function FollowUpSummary({plan,data,medications}:{plan:FollowUpPlan;data:FollowUpData;medications:MedicationSchedule[]}){const text=followUpSummary(data,plan,medications.map(x=>`${x.name} — ${x.scheduleText}`));return <section className='fu-card fu-summary'><h2>Ringkasan Follow-up</h2><pre>{text}</pre><div><button onClick={()=>{navigator.clipboard.writeText(text);toast.success('Ringkasan disalin')}}><Copy/> Salin</button><button onClick={()=>window.print()}><Printer/> Print / Browser PDF</button></div></section>}
export function SelectedSymptoms({plan,symptoms}:{plan:FollowUpPlan;symptoms:SymptomEntry[]}){const selected=symptoms.filter(x=>plan.selectedSymptomIds.includes(x.id));const toggle=(id:string)=>followUpRepository.savePlan({...plan,selectedSymptomIds:plan.selectedSymptomIds.includes(id)?plan.selectedSymptomIds.filter(x=>x!==id):[...plan.selectedSymptomIds,id],updatedAt:new Date().toISOString()});return <section className='fu-card'><h2>Hal yang ingin saya sampaikan</h2><p>Pilih catatan diary untuk dibawa ke kontrol. Lentera tidak menafsirkan artinya.</p>{symptoms.slice(0,10).map(x=><label className='fu-select-row' key={x.id}><input type='checkbox' checked={plan.selectedSymptomIds.includes(x.id)} onChange={()=>toggle(x.id)}/><span><strong>{x.symptom}</strong><small>{format(x.date)} · {x.severity}</small>{x.note&&<small>{x.note}</small>}</span></label>)}{!symptoms.length&&<p>Belum ada catatan di <Link to='/diary'>Diary Gejala</Link>.</p>}{selected.length>0&&<small>{selected.length} catatan dipilih.</small>}</section>}
export function DocumentLinks({plan,documents}:{plan:FollowUpPlan;documents:{id:string;title:string}[]}){const toggle=(id:string)=>followUpRepository.savePlan({...plan,linkedDocumentIds:plan.linkedDocumentIds.includes(id)?plan.linkedDocumentIds.filter(x=>x!==id):[...plan.linkedDocumentIds,id],updatedAt:new Date().toISOString()});return <section className='fu-card'><h2>Dokumen untuk kontrol ini</h2><p>Tautkan dokumen yang sudah ada—file tidak diunggah ulang.</p>{documents.map(x=><label className='fu-select-row' key={x.id}><input type='checkbox' checked={plan.linkedDocumentIds.includes(x.id)} onChange={()=>toggle(x.id)}/><FileText/><span>{x.title}</span></label>)}{!documents.length&&<p>Belum ada dokumen tersedia. <Link to='/documents'>Buka Document Vault</Link>.</p>}</section>}
export function SurvivorshipPanel(){return <section className='fu-card survivorship'><span>SURVIVORSHIP</span><h2>Kontrol dan pemulihan Anda</h2><p>Gunakan ruang ini untuk mengatur perawatan jangka panjang dan hal yang ingin dibahas pada kontrol berikutnya.</p><h3>Topik edukasi yang mungkin relevan</h3><ul>{['Kehidupan setelah terapi','Aktivitas fisik','Nutrisi','Efek jangka panjang','Kesehatan emosional','Kembali bekerja','Dukungan keluarga'].map(x=><li key={x}>{x}</li>)}</ul></section>}
export const taskTypes:FollowUpTaskType[]=['Konsultasi','Laboratorium','Imaging','Pemeriksaan fisik','Membawa hasil pemeriksaan','Mengambil obat','Administrasi','Lainnya']
