import { useEffect, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Bookmark, Check, ChevronRight, Copy, Download, Heart, Printer, RotateCcw, Search } from 'lucide-react'
import { toast } from 'sonner'
import { journeyStages } from '@/data/journey'
import { glossaryTerms } from '@/data/glossary'
import { questionGroups } from '@/data/questions'
import { checklists } from '@/data/checklists'
import { quizzes } from '@/data/quizzes'
import { myths } from '@/data/myths'
import { redFlags } from '@/data/redFlags'
import { reportTerms } from '@/data/reportTerms'
import { MedicalSafetyNotice } from '@/components/shared/MedicalSafetyNotice'
import { useLocalStorage } from '@/hooks/useLocalStorage'
import { trackEvent } from '@/lib/analytics'

const privacy=<p className='privacy-note'>Pilihan dan progres edukasi disimpan hanya di perangkat ini.</p>
function Head({title,lead}:{title:string;lead:string}) { useEffect(()=>{document.title=`${title} | Lentera Onko Vision`},[title]); return <header className='feature-head'><span>PENDAMPING EDUKASI</span><h1>{title}</h1><p>{lead}</p></header> }

export function JourneyPage(){const [params]=useSearchParams();const initial=params.get('stage')??'temuan';const [active,setActive]=useState(initial);const [done,setDone]=useLocalStorage<string[]>('lentera.journey.progress',[]);const [saved,setSaved]=useLocalStorage<string[]>('lentera.saved.journey',[]);const stage=journeyStages.find(x=>x.id===active)??journeyStages[0];const toggle=(id:string)=>setDone(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]); return <Feature><Head title='Perjalanan Kanker' lead='Pahami setiap tahap dengan tenang. Urutan perjalanan dapat berbeda untuk setiap orang.'/><div className='progress-card'><div><strong>{done.length} dari {journeyStages.length} tahap</strong><span>{Math.round(done.length/journeyStages.length*100)}% ditandai</span></div><progress max={journeyStages.length} value={done.length}/></div><div className='journey-tool'><ol className='stage-list'>{journeyStages.map(s=><li key={s.id}><button aria-selected={s.id===stage.id} className={s.id===stage.id?'active':''} onClick={()=>{setActive(s.id);trackEvent('journey_stage_opened',{stage:s.id})}}><span>{done.includes(s.id)?<Check/>:s.order}</span><div><strong>{s.title}</strong><small>{s.shortDescription}</small></div><ChevronRight/></button></li>)}</ol><section className='stage-detail' aria-live='polite'><span>TAHAP {stage.order} DARI 12</span><h2>{stage.title}</h2><h3>Apa yang terjadi di tahap ini?</h3><p>{stage.explanation}</p><h3>Mengapa tahap ini penting?</h3><p>{stage.importance}</p><InfoList title='Pemeriksaan atau proses yang umum dilakukan' items={stage.processes}/><InfoList title='Apa yang dapat dipersiapkan pasien?' items={stage.preparation}/><InfoList title='Pertanyaan yang bisa dibawa ke dokter' items={stage.questions}/><InfoList title='Tanda bahaya yang perlu diperhatikan' items={stage.redFlags}/><InfoList title='Artikel terkait' items={stage.relatedContent}/><div className='action-row'><button className='feature-button primary' onClick={()=>toggle(stage.id)}>{done.includes(stage.id)?<><Check/> Tahap sudah ditandai</>:'Saya sudah melewati tahap ini'}</button><button className='feature-button' onClick={()=>setSaved(v=>v.includes(stage.id)?v.filter(x=>x!==stage.id):[...v,stage.id])}><Bookmark/> {saved.includes(stage.id)?'Tersimpan':'Simpan tahap'}</button></div></section></div><button className='danger-link' onClick={()=>confirm('Reset seluruh progres perjalanan?')&&setDone([])}><RotateCcw/> Reset perjalanan</button>{privacy}</Feature>}

const situations=[['Saya menemukan gejala / benjolan','temuan','Anda mungkin sedang berada di tahap temuan / gejala.'],['Saya sedang menjalani pemeriksaan','pemeriksaan','Anda mungkin sedang berada di tahap pemeriksaan penunjang.'],['Saya baru mendapat diagnosis kanker','staging','Anda mungkin sedang berada di tahap diagnosis / staging.'],['Saya sedang menunggu hasil patologi','patologi','Anda mungkin sedang berada di tahap patologi.'],['Saya sedang mempersiapkan terapi','rencana','Anda mungkin sedang berada di tahap perencanaan terapi.'],['Saya sedang menjalani terapi','terapi','Anda mungkin sedang berada di tahap terapi.'],['Terapi saya selesai','pemulihan','Anda mungkin sedang berada di tahap pemulihan atau survivorship.'],['Saya mendampingi keluarga','caregiver','Kami memiliki panduan khusus untuk pendamping.']]
export function StartPage(){const [choice,setChoice]=useState<typeof situations[number]|null>(null);return <Feature><Head title='Di mana saya sekarang?' lead='Pilih situasi yang paling mendekati. Ini hanya membantu navigasi dan tidak menilai diagnosis.'/><h2>Apa situasi Anda saat ini?</h2><div className='choice-grid'>{situations.map(x=><button key={x[0]} onClick={()=>setChoice(x)} aria-pressed={choice?.[0]===x[0]}>{x[0]}<ChevronRight/></button>)}</div>{choice&&<section className='result-card' aria-live='polite'><span>NAVIGASI YANG DISARANKAN</span><h2>{choice[2]}</h2><p>Pilihan ini tidak menyimpulkan kondisi medis Anda.</p><Link className='feature-button primary' to={choice[1]==='caregiver'?'/caregiver':`/journey?stage=${choice[1]}`}>Buka panduan <ChevronRight/></Link></section>}{privacy}</Feature>}

export function GlossaryPage(){const [q,setQ]=useState('');const [letter,setLetter]=useState('Semua');const [cat,setCat]=useState('Semua');const [selected,setSelected]=useState<string|null>(null);const [favorites,setFavorites]=useLocalStorage<string[]>('lentera.saved.glossary',[]);const [recent,setRecent]=useLocalStorage<string[]>('lentera.glossary.recent',[]);const cats=['Semua',...new Set(glossaryTerms.map(x=>x.category))];const filtered=glossaryTerms.filter(x=>(!q||`${x.term} ${x.definition}`.toLowerCase().includes(q.toLowerCase()))&&(letter==='Semua'||x.term[0]===letter)&&(cat==='Semua'||x.category===cat));const term=glossaryTerms.find(x=>x.id===selected);const open=(id:string)=>{setSelected(id);setRecent(v=>[id,...v.filter(x=>x!==id)].slice(0,5));trackEvent('glossary_term_opened',{term:id})};return <Feature><Head title='Glosarium Onkologi' lead='Cari istilah medis dan siapkan pertanyaan untuk percakapan dengan dokter.'/><div className='sticky-filter'><label><Search/><span className='sr-only'>Cari istilah</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder='Cari istilah atau definisi…'/></label><select aria-label='Filter kategori' value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select></div><div className='alphabet' aria-label='Filter huruf'>{['Semua',...new Set(glossaryTerms.map(x=>x.term[0]))].map(x=><button aria-pressed={letter===x} onClick={()=>setLetter(x)} key={x}>{x}</button>)}</div>{recent.length>0&&<p className='recent'>Baru dilihat: {recent.map(id=>glossaryTerms.find(x=>x.id===id)?.term).filter(Boolean).join(' · ')}</p>}<div className='term-grid'>{filtered.map(x=><article key={x.id}><button className='term-open' onClick={()=>open(x.id)}><span>{x.category}</span><h2>{x.term}</h2><p>{x.definition}</p></button><button className='save-icon' aria-label={`Simpan ${x.term}`} aria-pressed={favorites.includes(x.id)} onClick={()=>setFavorites(v=>v.includes(x.id)?v.filter(i=>i!==x.id):[...v,x.id])}><Heart fill={favorites.includes(x.id)?'currentColor':'none'}/></button></article>)}</div>{!filtered.length&&<Empty text='Tidak ada istilah yang cocok. Coba kata lain.'/ >}{term&&<div className='detail-sheet' role='dialog' aria-modal='true' aria-label={term.term}><button className='sheet-close' onClick={()=>setSelected(null)}>Tutup</button><span>{term.category}</span><h2>{term.term}</h2><p className='definition'>{term.definition}</p><h3>Penjelasan lebih lanjut</h3><p>{term.detail}</p><h3>Mengapa istilah ini penting?</h3><p>{term.importance}</p><h3>Pertanyaan untuk dokter</h3><blockquote>{term.doctorQuestion}</blockquote><p><strong>Istilah terkait:</strong> {term.related.join(', ')}</p></div>}{privacy}</Feature>}

export function DecodePage(){const [cat,setCat]=useState('Patologi');return <Feature><Head title='Decode My Report' lead='Kenali istilah umum dalam laporan tanpa menafsirkan hasil atau membuat diagnosis.'/><MedicalSafetyNotice/><div className='tab-buttons' role='tablist'>{Object.keys(reportTerms).map(x=><button role='tab' aria-selected={cat===x} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className='explain-grid'>{Object.entries(reportTerms[cat]).map(([term,text])=><article key={term}><span>ISTILAH UMUM</span><h2>{term}</h2><p><strong>Istilah ini biasanya digunakan untuk</strong> {text}</p><small>Makna klinis hasil Anda perlu didiskusikan dengan dokter yang menangani Anda.</small></article>)}</div></Feature>}

export function QuestionsPage(){const [selected,setSelected]=useLocalStorage<string[]>('lentera.questions.selected',[]);const [custom,setCustom]=useLocalStorage<string[]>('lentera.questions.custom',[]);const [draft,setDraft]=useState('');const all=[...selected,...custom];const text=`Daftar Pertanyaan Saya\n\n${all.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\nLentera Onko Vision — materi edukatif`;const add=()=>{if(!draft.trim())return;setCustom(v=>[...v,draft.trim()]);setDraft('');trackEvent('question_added')};return <Feature><Head title='Pertanyaan untuk Dokter Onkologi' lead='Susun daftar agar hal penting tidak terlupa saat konsultasi.'/><MedicalSafetyNotice/>{Object.entries(questionGroups).map(([cat,items])=><section className='question-section' key={cat}><h2>{cat}</h2>{items.map(q=><label key={q}><input type='checkbox' checked={selected.includes(q)} onChange={()=>setSelected(v=>v.includes(q)?v.filter(x=>x!==q):[...v,q])}/><span><Check/></span>{q}</label>)}</section>)}<div className='custom-input'><label htmlFor='custom-question'>Tambahkan pertanyaan sendiri</label><div><input id='custom-question' value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder='Tulis pertanyaan…'/><button onClick={add}>Tambah</button></div></div><section className='my-list'><h2>Daftar Pertanyaan Saya</h2>{all.length?<ol>{all.map((q,i)=><li key={`${q}-${i}`}>{q}{custom.includes(q)&&<button aria-label={`Hapus ${q}`} onClick={()=>setCustom(v=>v.filter(x=>x!==q))}>×</button>}</li>)}</ol>:<Empty text='Pilih atau tambahkan pertanyaan untuk membuat daftar.'/>}<div className='action-row'><button onClick={()=>navigator.clipboard.writeText(text).then(()=>toast.success('Daftar disalin'))}><Copy/> Copy</button><button onClick={()=>window.print()}><Printer/> Print</button><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'}));a.download='pertanyaan-dokter.txt';a.click();URL.revokeObjectURL(a.href)}}><Download/> Download .txt</button><button onClick={()=>confirm('Reset daftar pertanyaan?')&&(setSelected([]),setCustom([]))}><RotateCcw/> Reset</button></div></section>{privacy}</Feature>}

export function PreparePage(){const [cat,setCat]=useState('Kemoterapi');const [status,setStatus]=useLocalStorage<Record<string,string[]>>('lentera.checklists',{});const items=checklists[cat];const done=status[cat]??[];const toggle=(x:string)=>setStatus(s=>({...s,[cat]:done.includes(x)?done.filter(i=>i!==x):[...done,x]}));return <Feature><Head title='Checklist Persiapan' lead='Persiapkan hal praktis untuk konsultasi, pemeriksaan, terapi, dan follow-up.'/><MedicalSafetyNotice/><div className='tab-buttons'>{Object.keys(checklists).map(x=><button className={cat===x?'active':''} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className='checklist-panel'><div className='progress-card'><div><strong>{done.length} dari {items.length} selesai</strong><span>Simpan otomatis</span></div><progress max={items.length} value={done.length}/></div>{items.map(x=><label className={done.includes(x)?'done':''} key={x}><input type='checkbox' checked={done.includes(x)} onChange={()=>toggle(x)}/><span><Check/></span>{x}</label>)}<button className='danger-link' onClick={()=>confirm(`Reset checklist ${cat}?`)&&setStatus(s=>({...s,[cat]:[]}))}><RotateCcw/> Reset checklist</button></div>{privacy}</Feature>}

export function QuizPage(){const [topic,setTopic]=useState(quizzes[0].id);const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<number[]>([]);const [completed,setCompleted]=useLocalStorage<string[]>('lentera.quiz.completed',[]);const quiz=quizzes.find(x=>x.id===topic)!;const answer=answers[index];const choose=(n:number)=>{if(answer!==undefined)return;setAnswers(v=>{const next=[...v];next[index]=n;return next})};const next=()=>{if(index<4)setIndex(i=>i+1);else{setCompleted(v=>v.includes(topic)?v:[...v,topic]);trackEvent('quiz_completed',{quiz:topic})}};const reset=(id:string)=>{setTopic(id);setIndex(0);setAnswers([])};return <Feature><Head title='Kuis Edukasi Mini' lead='Uji pemahaman dengan santai. Jawaban digunakan hanya untuk membantu belajar.'/><div className='quiz-topics'>{quizzes.map(q=><button aria-pressed={q.id===topic} onClick={()=>reset(q.id)} key={q.id}>{completed.includes(q.id)&&<Check/>}{q.title}</button>)}</div>{completed.includes(topic)&&index===4&&answer!==undefined?<section className='result-card'><span>SELESAI DIPELAJARI</span><h2>{quiz.title}</h2><h3>Yang sudah Anda pahami</h3><p>Konsep dasar, peran tim kesehatan, dan pentingnya menyiapkan pertanyaan.</p><h3>Yang masih bisa dipelajari</h3><p>Buka perjalanan, glosarium, atau artikel terkait untuk memperdalam istilah yang belum familier.</p><button className='feature-button' onClick={()=>{setIndex(0);setAnswers([]);setCompleted(v=>v.filter(x=>x!==topic))}}>Pelajari ulang</button></section>:<section className='quiz-card'><div className='progress-card'><div><strong>Pertanyaan {index+1} dari 5</strong><span>{quiz.title}</span></div><progress max='5' value={index+1}/></div><h2>{quiz.questions[index].prompt}</h2><div className='quiz-options'>{quiz.questions[index].options.map((x,n)=><button disabled={answer!==undefined} className={answer===n?(n===quiz.questions[index].answer?'correct':'incorrect'):''} onClick={()=>choose(n)} key={x}>{x}</button>)}</div>{answer!==undefined&&<div className='feedback' aria-live='polite'><strong>{answer===quiz.questions[index].answer?'Tepat. Mari lanjutkan pemahaman.':'Belum tepat. Mari pahami konsepnya.'}</strong><p>{quiz.questions[index].explanation}</p><button className='feature-button primary' onClick={next}>{index===4?'Selesaikan':'Pertanyaan berikutnya'} <ChevronRight/></button></div>}</section>}{privacy}</Feature>}

export function MythFactPage(){const [viewed,setViewed]=useLocalStorage<string[]>('lentera.myths.viewed',[]);const [revealed,setRevealed]=useState<string[]>([]);return <Feature><Head title='Mitos vs Fakta' lead='Buka tiap kartu untuk melihat penjelasan yang bertanggung jawab.'/><div className='myth-cards'>{myths.map(x=><article className={revealed.includes(x.id)?'revealed':''} key={x.id}><span>MITOS</span><h2>“{x.myth}”</h2>{revealed.includes(x.id)?<><h3>FAKTA</h3><p>{x.fact}</p><button onClick={()=>setViewed(v=>v.includes(x.id)?v:[...v,x.id])}>{viewed.includes(x.id)?<><Check/> Sudah tahu</>:'Tandai sudah tahu'}</button></>:<button onClick={()=>setRevealed(v=>[...v,x.id])}>Pelajari lebih lanjut <ChevronRight/></button>}</article>)}</div>{privacy}</Feature>}

export function RedFlagsPage(){return <Feature><Head title='Kenali Tanda Bahaya' lead='Panduan ini bukan pemeriksa gejala dan tidak menghitung risiko medis.'/><MedicalSafetyNotice emergency/><div className='redflag-grid'>{Object.entries(redFlags).map(([cat,items])=><section key={cat}><h2>{cat}</h2><ul>{items.map(x=><li key={x}><span>!</span>{x}</li>)}</ul><p>Hubungi tim kesehatan yang menangani untuk instruksi yang sesuai.</p></section>)}</div><MedicalSafetyNotice/></Feature>}

const caregiverSections=['Saat diagnosis','Mendampingi konsultasi','Membantu mencatat informasi','Persiapan terapi','Nutrisi dan aktivitas','Dukungan emosional','Mengelola jadwal','Menjaga kesehatan caregiver'];
export function CaregiverPage(){const tasks=['Catat pertanyaan pasien sebelum konsultasi','Bawa dokumen dan daftar obat yang diperlukan','Catat penjelasan dan jadwal tindak lanjut','Tanyakan tanda bahaya dan kontak fasilitas','Sisihkan waktu untuk istirahat caregiver'];const [done,setDone]=useLocalStorage<string[]>('lentera.caregiver.checklist',[]);return <Feature><Head title='Mode Caregiver' lead='Panduan praktis untuk mendampingi tanpa melupakan kesehatan diri sendiri.'/><div className='care-sections'>{caregiverSections.map((x,i)=><article key={x}><span>0{i+1}</span><h2>{x}</h2><p>{i===7?'Istirahat, meminta bantuan, dan menjaga kebutuhan diri adalah bagian penting dari pendampingan.':'Dengarkan kebutuhan pasien, bantu mencatat hal penting, dan sepakati bentuk dukungan yang diinginkan.'}</p></article>)}</div><section className='checklist-panel'><h2>Checklist Pendamping</h2>{tasks.map(x=><label className={done.includes(x)?'done':''} key={x}><input type='checkbox' checked={done.includes(x)} onChange={()=>setDone(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x])}/><span><Check/></span>{x}</label>)}</section>{privacy}</Feature>}

export function LearningPage(){const [journey]=useLocalStorage<string[]>('lentera.journey.progress',[]);const [recent]=useLocalStorage<string[]>('lentera.glossary.recent',[]);const [checks]=useLocalStorage<Record<string,string[]>>('lentera.checklists',{});const [quiz]=useLocalStorage<string[]>('lentera.quiz.completed',[]);const [articles]=useLocalStorage<{readMap:Record<string,boolean>}>('onko-radiasi-learning-progress',{readMap:{}});const checked=Object.values(checks).reduce((n,x)=>n+x.length,0);const categories=[['Diagnosis',Math.min(100,(journey.filter(x=>['temuan','konsultasi','pemeriksaan','biopsi','patologi','staging'].includes(x)).length+recent.length)*10)],['Terapi',Math.min(100,(journey.filter(x=>['rencana','terapi','monitoring'].includes(x)).length+checked)*8)],['Caregiver',0],['Survivorship',journey.includes('survivorship')?100:0]] as [string,number][];return <Feature><Head title='Perjalanan Belajar Anda' lead='Ringkasan tenang tentang materi yang sudah dibuka dan hal yang masih dapat dipelajari.'/><div className='learning-summary'>{[['Artikel dibuka',Object.keys(articles.readMap??{}).length],['Istilah dilihat',recent.length],['Tahap perjalanan',journey.length],['Tugas checklist',checked],['Kuis selesai',quiz.length]].map(([x,n])=><article key={x}><strong>{n}</strong><span>{x}</span></article>)}</div><div className='learning-bars'>{categories.map(([x,n])=><div key={x}><label><strong>{x}</strong><span>{n}%</span></label><progress max='100' value={n}/></div>)}</div><p>Tidak ada streak atau peringkat. Belajar dapat dilakukan sesuai energi dan kebutuhan Anda.</p>{privacy}</Feature>}

export function SavedPage(){const [terms,setTerms]=useLocalStorage<string[]>('lentera.saved.glossary',[]);const [stages,setStages]=useLocalStorage<string[]>('lentera.saved.journey',[]);const [questions]=useLocalStorage<string[]>('lentera.questions.selected',[]);const [custom]=useLocalStorage<string[]>('lentera.questions.custom',[]);const [checks]=useLocalStorage<Record<string,string[]>>('lentera.checklists',{});const [learning]=useLocalStorage<{bookmarks?:string[]}>('onko-radiasi-learning-progress',{});return <Feature><Head title='Tersimpan untuk Nanti' lead='Semua pilihan tersimpan lokal di browser ini dan dapat dihapus kapan saja.'/><SavedSection title='Artikel Tersimpan' items={(learning.bookmarks??[]).map(x=>`Artikel ${x}`)}/><SavedSection title='Istilah Tersimpan' items={terms.map(id=>glossaryTerms.find(x=>x.id===id)?.term??id)} onClear={()=>setTerms([])}/><SavedSection title='Tahap Perjalanan Tersimpan' items={stages.map(id=>journeyStages.find(x=>x.id===id)?.title??id)} onClear={()=>setStages([])}/><SavedSection title='Pertanyaan Saya' items={[...questions,...custom]}/><SavedSection title='Checklist Saya' items={Object.entries(checks).filter(([,v])=>v.length).map(([x,v])=>`${x}: ${v.length} selesai`)}/>{privacy}</Feature>}

export function SearchPage(){const [params,setParams]=useSearchParams();const input=useRef<HTMLInputElement>(null);const q=params.get('q')??'';useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName)){e.preventDefault();input.current?.focus()}};addEventListener('keydown',fn);return()=>removeEventListener('keydown',fn)},[]);const match=(s:string)=>q.length>1&&s.toLowerCase().includes(q.toLowerCase());const groups=[['Istilah',glossaryTerms.filter(x=>match(x.term+' '+x.definition)).map(x=>({label:x.term,to:'/glossary'}))],['Perjalanan',journeyStages.filter(x=>match(x.title+' '+x.shortDescription)).map(x=>({label:x.title,to:`/journey?stage=${x.id}`}))],['Mitos & Fakta',myths.filter(x=>match(x.myth+' '+x.fact)).map(x=>({label:x.myth,to:'/myth-fact'}))],['FAQ',[{label:'Kapan harus segera mencari pertolongan?',to:'/red-flags'}].filter(x=>match(x.label))]] as const;return <Feature><Head title='Pencarian Lentera' lead='Cari istilah, tahap perjalanan, FAQ, serta mitos dan fakta.'/><label className='global-search'><Search/><span className='sr-only'>Cari semua konten</span><input ref={input} autoFocus value={q} onChange={e=>setParams(e.target.value?{q:e.target.value}:{})} placeholder='Ketik minimal 2 huruf…'/><kbd>/</kbd></label>{q.length<2?<Empty text='Ketik kata seperti biopsi, terapi, atau demam.'/>:groups.map(([title,items])=><SavedSection key={title} title={title} items={items.map(x=>x.label)} links={items.map(x=>x.to)}/>)}</Feature>}

function Feature({children}:{children:React.ReactNode}){return <div className='feature-page'><div className='feature-shell'>{children}</div></div>}
function InfoList({title,items}:{title:string;items:string[]}){return <section className='info-list'><h3>{title}</h3><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></section>}
function Empty({text}:{text:string}){return <p className='empty-state'>{text}</p>}
function SavedSection({title,items,onClear,links}:{title:string;items:string[];onClear?:()=>void;links?:readonly string[]}){return <section className='saved-section'><div><h2>{title}</h2>{onClear&&items.length>0&&<button onClick={onClear}>Hapus semua</button>}</div>{items.length?<ul>{items.map((x,i)=><li key={`${x}-${i}`}>{links?<Link to={links[i]}>{x}<ChevronRight/></Link>:x}</li>)}</ul>:<Empty text='Belum ada item tersimpan.'/ >}</section>}
