import type { MedicalArticle } from '@/types/content'

export const insightArticles: MedicalArticle[] = [{
  id: 'article-global-cancer-burden-2022',
  slug: 'potret-kanker-dunia-20-juta-kasus-baru',
  title: 'Potret Kanker Dunia: Memahami Angka 20 Juta Kasus Baru',
  subtitle: 'Data global terbaru membantu kita melihat skala masalah—tanpa mengubah angka populasi menjadi ramalan pribadi',
  excerpt: 'IARC memperkirakan hampir 20 juta kasus kanker baru pada 2022. Pelajari arti angka itu, proyeksi 2050, dan mengapa akses layanan ikut menentukan dampaknya.',
  categoryId: 'dasar-kanker',
  tags: ['data kanker', 'epidemiologi', 'globocan', 'pencegahan'],
  keywords: ['20 juta kasus kanker', '35 juta 2050', 'beban kanker dunia', 'IARC'],
  glossaryTerms: ['Insidensi', 'Prevalensi', 'Mortalitas'],
  authorId: 'editorial-team',
  status: 'published',
  featured: true,
  readingTime: 7,
  createdAt: '2026-08-24',
  updatedAt: '2026-08-24',
  publishedAt: '2026-08-24',
  nextReviewAt: '2027-02-24',
  body: [
    { id: 'takeaways', type: 'key_takeaway', items: [
      'Hampir 20 juta kasus kanker baru dan 9,7 juta kematian diperkirakan terjadi di dunia pada 2022.',
      'Sekitar 53,5 juta orang hidup dalam lima tahun setelah diagnosis kanker pada akhir 2022.',
      'IARC memproyeksikan lebih dari 35 juta kasus baru per tahun pada 2050—naik 77% dibanding 2022.',
      'Angka populasi membantu perencanaan layanan; angka ini bukan prediksi risiko atau hasil terapi seseorang.',
    ]},
    { id: 'angka-utama', type: 'heading', level: 2, text: 'Empat angka yang memberi konteks' },
    { id: 'p-1', type: 'paragraph', text: 'Global Cancer Observatory dari International Agency for Research on Cancer (IARC) memperkirakan 19.976.499 kasus baru dan 9.743.832 kematian akibat kanker di dunia pada 2022. Angka yang dibulatkan—20 juta dan 9,7 juta—lebih mudah dibaca, tetapi tetap merupakan estimasi berbasis sumber data yang kualitas dan kelengkapannya berbeda antarnegara.' },
    { id: 'global-chart', type: 'image', src: '/images/cancer-burden-2022-2050.svg', alt: 'Grafik batang: 20 juta kasus baru kanker pada 2022 dibandingkan proyeksi lebih dari 35 juta pada 2050, meningkat 77 persen.', caption: 'Kasus baru kanker per tahun diproyeksikan meningkat 77% antara 2022 dan 2050. Sumber data: IARC.' },
    { id: 'data-table', type: 'table', caption: 'Ringkasan estimasi beban kanker dunia', headers: ['Indikator', 'Angka', 'Cara membacanya'], rows: [
      ['Kasus baru, 2022', '19.976.499', 'Orang yang diperkirakan mendapat diagnosis baru dalam satu tahun'],
      ['Kematian, 2022', '9.743.832', 'Kematian yang diperkirakan berkaitan dengan kanker dalam satu tahun'],
      ['Prevalensi 5 tahun', '53.504.187', 'Orang yang masih hidup dan didiagnosis dalam lima tahun sebelumnya'],
      ['Proyeksi kasus baru, 2050', '>35 juta', 'Proyeksi tahunan; sekitar 77% lebih tinggi daripada 2022'],
    ]},
    { id: 'risiko-populasi', type: 'heading', level: 2, text: 'Satu dari lima bukan berarti jadwal hidup seseorang' },
    { id: 'p-2', type: 'paragraph', text: 'IARC merangkum risiko seumur hidup secara global sebagai sekitar satu dari lima orang mengalami kanker. Sekitar satu dari sembilan laki-laki dan satu dari dua belas perempuan meninggal akibat kanker. Ini adalah rata-rata populasi: usia, jenis kanker, paparan, riwayat keluarga, akses skrining, dan banyak faktor lain membuat risiko individu berbeda.' },
    { id: 'population-note', type: 'callout', title: 'Ilmu baru: bedakan insidensi dan prevalensi', text: 'Insidensi menghitung kasus baru selama periode tertentu. Prevalensi menghitung orang yang hidup dengan atau setelah diagnosis pada suatu waktu. Keduanya menjawab pertanyaan berbeda dan tidak boleh dipertukarkan.' },
    { id: 'why-rise', type: 'heading', level: 2, text: 'Mengapa proyeksi 2050 meningkat?' },
    { id: 'p-3', type: 'paragraph', text: 'Kenaikan proyeksi tidak berarti kanker tiba-tiba menjadi 77% lebih ganas. Pertumbuhan dan penuaan penduduk menyumbang peningkatan jumlah kasus. Perubahan paparan faktor risiko—termasuk tembakau, alkohol, obesitas, dan polusi udara—serta ketimpangan pembangunan juga berperan.' },
    { id: 'what-matters', type: 'heading', level: 2, text: 'Apa maknanya untuk layanan kesehatan?' },
    { id: 'p-4', type: 'paragraph', text: 'Jumlah kasus yang lebih besar berarti kebutuhan yang ikut bertambah: pencegahan, deteksi dini yang sesuai bukti, patologi, operasi, obat, radioterapi, perawatan paliatif, dan dukungan penyintas. IARC menekankan bahwa dampak kenaikan tidak terbagi merata; negara dengan indeks pembangunan lebih rendah diperkirakan menghadapi kenaikan proporsional yang lebih besar.' },
    { id: 'warning', type: 'medical_warning', text: 'Statistik global tidak dapat menentukan apakah Anda mengalami kanker. Bila ada gejala yang menetap, perubahan tubuh yang mengkhawatirkan, atau pertanyaan tentang skrining sesuai usia dan risiko, diskusikan dengan tenaga kesehatan.' },
    { id: 'evidence', type: 'evidence_note', text: 'Angka dalam artikel menggunakan estimasi GLOBOCAN 2022. Proyeksi adalah skenario berbasis perubahan demografi dan pola risiko, bukan kepastian. Data baru dapat memperbarui estimasi ini.' },
    { id: 'references', type: 'references' },
    { id: 'disclaimer', type: 'disclaimer', text: 'Informasi ini bersifat edukatif dan tidak menggantikan diagnosis, pemeriksaan, atau rencana terapi dari tenaga kesehatan yang merawat Anda.' },
  ],
  references: [
    { id: 'iarc-global-burden-2022', title: 'Global cancer burden growing, amidst mounting need for services', authors: 'International Agency for Research on Cancer', year: 2024, url: 'https://www.iarc.who.int/news-events/global-cancer-burden-growing-amidst-mounting-need-for-services/', sourceType: 'government' },
    { id: 'gco-world-factsheet', title: 'World Fact Sheet: GLOBOCAN 2022', authors: 'Global Cancer Observatory, International Agency for Research on Cancer', year: 2024, url: 'https://gco.iarc.who.int/media/globocan/factsheets/populations/900-world-fact-sheet.pdf', sourceType: 'government' },
  ],
  revisionHistory: [{ version: 1, date: '2026-08-24', summary: 'Publikasi awal ringkasan data GLOBOCAN 2022 dengan visualisasi dan catatan interpretasi.', editor: 'Tim Editorial Lentera' }],
  seo: { title: 'Potret Kanker Dunia: Data GLOBOCAN 2022 | Lentera', description: 'Memahami 20 juta kasus kanker baru, 9,7 juta kematian, dan proyeksi beban kanker dunia pada 2050.', canonicalSlug: '/articles/potret-kanker-dunia-20-juta-kasus-baru', medicalWebPage: true },
  relatedArticleIds: ['article-stage', 'article-survivorship'],
  relatedJourneyStage: 'Edukasi',
}]
