import type { MedicalArticle } from '@/types/content'

export const radiationNewsArticles: MedicalArticle[] = [{
  id: 'article-news-adaptive-radiotherapy',
  slug: 'radioterapi-adaptif-menyesuaikan-perubahan-tubuh',
  title: 'Radioterapi Adaptif: Menyesuaikan Terapi dengan Perubahan Tubuh',
  subtitle: 'Teknologi pencitraan membantu tim onkologi radiasi mengevaluasi kembali rencana terapi ketika anatomi pasien berubah',
  excerpt: 'Radioterapi adaptif memungkinkan tim medis menilai perubahan anatomi selama rangkaian terapi dan, bila diperlukan, memperbarui rencana penyinaran.',
  categoryId: 'radioterapi',
  tags: ['onkologi radiasi', 'radioterapi adaptif', 'teknologi kanker', 'keselamatan pasien'],
  keywords: ['adaptive radiotherapy', 'radioterapi presisi', 'perencanaan radiasi', 'image-guided radiotherapy'],
  glossaryTerms: ['Radioterapi'],
  authorId: 'editorial-team',
  status: 'published',
  featured: true,
  readingTime: 7,
  createdAt: '2026-08-25',
  updatedAt: '2026-08-25',
  publishedAt: '2026-08-25',
  nextReviewAt: '2027-02-25',
  body: [
    { id: 'takeaways', type: 'key_takeaway', items: [
      'Posisi tumor dan organ sehat dapat berubah selama rangkaian radioterapi.',
      'Radioterapi adaptif menilai apakah rencana penyinaran perlu diperbarui berdasarkan pencitraan dan evaluasi tim klinis.',
      'Adaptasi tidak selalu diperlukan dan tidak otomatis membuat terapi lebih baik untuk setiap pasien.',
      'Keputusan tetap mempertimbangkan jenis kanker, tujuan terapi, perubahan anatomi, manfaat, dan sumber daya klinis.',
    ]},
    { id: 'news-angle', type: 'heading', level: 2, text: 'Apa yang baru dalam pendekatan ini?' },
    { id: 'p-1', type: 'paragraph', text: 'Radioterapi selalu direncanakan dengan cermat agar dosis mencapai sasaran sambil membatasi paparan pada jaringan sehat. Dalam radioterapi adaptif, tim tidak hanya mengandalkan gambaran anatomi pada awal perencanaan. Pencitraan selama rangkaian terapi dapat digunakan untuk melihat apakah perubahan tubuh cukup bermakna sehingga rencana perlu dihitung dan diperiksa kembali.' },
    { id: 'p-2', type: 'paragraph', text: 'Pendekatan ini semakin mendapat perhatian seiring berkembangnya mesin radioterapi yang dipadukan dengan pencitraan dan perangkat lunak perencanaan. Namun, istilah “adaptif” menggambarkan sebuah proses klinis, bukan satu mesin tertentu. Dokter onkologi radiasi, fisikawan medis, radiografer atau terapis radiasi, serta tenaga lain tetap berperan dalam pemeriksaan mutu dan keselamatan.' },
    { id: 'why-change', type: 'heading', level: 2, text: 'Mengapa rencana terapi mungkin perlu disesuaikan?' },
    { id: 'p-3', type: 'paragraph', text: 'Selama beberapa hari atau minggu terapi, ukuran tumor dapat berubah. Berat badan, isi kandung kemih atau usus, pembengkakan, dan posisi organ di sekitar sasaran juga dapat berbeda. Tidak semua perubahan memengaruhi distribusi dosis secara berarti. Tim klinis menilai perubahan tersebut sebelum memutuskan apakah rencana awal tetap aman digunakan atau perlu diadaptasi.' },
    { id: 'workflow', type: 'table', caption: 'Gambaran sederhana alur radioterapi adaptif', headers: ['Tahap', 'Apa yang dilakukan'], rows: [
      ['Pencitraan', 'Mengambil gambaran anatomi pasien pada posisi terapi.'],
      ['Evaluasi', 'Membandingkan sasaran dan organ sehat dengan rencana yang digunakan.'],
      ['Perencanaan ulang', 'Menghitung rencana baru bila perubahan dinilai bermakna.'],
      ['Verifikasi', 'Melakukan pemeriksaan klinis, dosis, dan mutu sebelum penyinaran.'],
    ]},
    { id: 'not-automatic', type: 'callout', title: 'Lebih baru bukan berarti selalu lebih tepat', text: 'Radioterapi adaptif dapat menambah waktu, pekerjaan perencanaan, dan pemeriksaan mutu. Manfaatnya bergantung pada situasi klinis. Rencana radioterapi standar yang telah diverifikasi tetap dapat menjadi pilihan yang tepat.' },
    { id: 'patient-experience', type: 'heading', level: 2, text: 'Apa artinya bagi pasien?' },
    { id: 'p-4', type: 'paragraph', text: 'Bagi sebagian pasien, sesi tertentu dapat berlangsung lebih lama karena ada pencitraan dan evaluasi tambahan. Pasien mungkin tetap diminta mengikuti persiapan khusus, misalnya datang dengan kondisi kandung kemih tertentu atau menjaga posisi yang sama. Instruksi berbeda menurut lokasi terapi dan kebijakan fasilitas.' },
    { id: 'questions', type: 'heading', level: 2, text: 'Pertanyaan yang dapat dibawa saat konsultasi' },
    { id: 'question-list', type: 'bullet_list', items: [
      'Apa tujuan radioterapi saya dan bagaimana keberhasilannya akan dinilai?',
      'Apakah perubahan anatomi akan dipantau selama terapi?',
      'Persiapan apa yang perlu saya lakukan sebelum setiap sesi?',
      'Keluhan apa yang perlu segera saya laporkan?',
    ]},
    { id: 'faq', type: 'faq', items: [
      { question: 'Apakah radioterapi adaptif sama dengan radioterapi yang dipandu gambar?', answer: 'Keduanya berkaitan, tetapi tidak selalu sama. Pencitraan dapat membantu memastikan posisi sebelum terapi. Pada proses adaptif, informasi tersebut juga dapat digunakan untuk menilai dan memperbarui rencana dosis bila diperlukan.' },
      { question: 'Apakah adaptasi menjamin efek samping lebih sedikit?', answer: 'Tidak. Tujuannya adalah menjaga kesesuaian distribusi dosis saat anatomi berubah, tetapi manfaat dan efek samping tetap dipengaruhi banyak faktor. Tim yang merawat dapat menjelaskan perkiraan untuk situasi Anda.' },
    ]},
    { id: 'warning', type: 'medical_warning', text: 'Jangan melewatkan sesi atau mengubah persiapan radioterapi tanpa berbicara dengan unit radioterapi. Segera laporkan gejala baru atau memburuk melalui jalur kontak yang diberikan tim perawatan.' },
    { id: 'evidence', type: 'evidence_note', text: 'Artikel ini menjelaskan prinsip umum radioterapi dan adaptasi rencana. Ketersediaan teknologi, alur kerja, serta indikasi klinis berbeda antar fasilitas dan terus berkembang.' },
    { id: 'references', type: 'references' },
    { id: 'disclaimer', type: 'disclaimer', text: 'Informasi ini bersifat edukatif dan tidak menggantikan diagnosis, pemeriksaan, atau rencana terapi dari tenaga kesehatan yang merawat Anda.' },
  ],
  references: [
    { id: 'nci-radiation-therapy', title: 'Radiation Therapy to Treat Cancer', authors: 'National Cancer Institute', url: 'https://www.cancer.gov/about-cancer/treatment/types/radiation-therapy', sourceType: 'government' },
    { id: 'iaea-radiotherapy', title: 'Radiotherapy', authors: 'International Atomic Energy Agency', url: 'https://www.iaea.org/topics/radiotherapy', sourceType: 'organization' },
  ],
  revisionHistory: [{ version: 1, date: '2026-08-25', summary: 'Publikasi awal berita edukatif tentang prinsip dan batasan radioterapi adaptif.', editor: 'Tim Editorial Lentera' }],
  seo: {
    title: 'Radioterapi Adaptif dan Perubahan Tubuh | Lentera',
    description: 'Memahami cara pencitraan membantu tim onkologi radiasi menilai perubahan anatomi dan menyesuaikan rencana terapi bila diperlukan.',
    canonicalSlug: '/articles/radioterapi-adaptif-menyesuaikan-perubahan-tubuh',
    medicalWebPage: true,
  },
  relatedArticleIds: ['article-radiation', 'article-nutrition'],
  relatedJourneyStage: 'Terapi',
}]
