import { references } from '@/content/references'
import { article, blocks, common } from './helpers'

export const supportArticles = [
  article({ id:'article-palliative', slug:'apa-itu-palliative-care', title:'Apa Itu Palliative Care?', excerpt:'Perawatan paliatif berfokus pada kualitas hidup dan dukungan gejala, serta dapat diberikan bersamaan dengan terapi kanker.', categoryId:'paliatif', tags:['palliative care','support'], keywords:['gejala','kualitas hidup'], glossaryTerms:['Paliatif'], status:'published', readingTime:5, ...common(references.whoPalliative), relatedArticleIds:['article-caregiver','article-survivorship'], relatedJourneyStage:'Dukungan', body:blocks(['Paliatif tidak hanya untuk akhir kehidupan.','Dukungan dapat mencakup gejala, emosi, sosial, dan komunikasi.','Tanyakan kapan layanan paliatif tersedia di tempat Anda.'],'Fokus perawatan',['Perawatan paliatif bertujuan membantu pasien dan keluarga menghadapi masalah yang berkaitan dengan penyakit serius. Kebutuhan setiap orang berbeda.','Layanan ini dapat berjalan bersama pengobatan kanker dan tidak berarti tim menghentikan seluruh terapi.']) }),
  article({ id:'article-caregiver', slug:'panduan-caregiver-saat-konsultasi', title:'Panduan Caregiver Saat Konsultasi', excerpt:'Caregiver dapat membantu menyiapkan catatan, memastikan pertanyaan terbahas, dan mendukung keputusan pasien.', categoryId:'caregiver', tags:['caregiver','consultation'], keywords:['pendamping','pertanyaan dokter'], glossaryTerms:['Caregiver'], status:'published', readingTime:5, ...common(references.nciCaregiver), relatedArticleIds:['article-palliative','article-fever'], relatedJourneyStage:'Konsultasi', body:blocks(['Sepakati peran caregiver bersama pasien.','Bawa daftar obat, keluhan, dan pertanyaan prioritas.','Hormati privasi dan pilihan pasien.'],'Sebelum konsultasi',['Tanyakan kepada pasien dukungan apa yang ia inginkan. Buat daftar singkat pertanyaan utama dan catat perubahan gejala, tanpa menafsirkan sendiri penyebabnya.','Saat konsultasi, ulangi kembali rencana tindak lanjut untuk memastikan pemahaman. Minta izin sebelum membagikan informasi pribadi pasien.']) }),
  article({ id:'article-survivorship', slug:'kehidupan-setelah-terapi-kanker', title:'Kehidupan Setelah Terapi Kanker', excerpt:'Masa setelah terapi dapat melibatkan pemantauan, pemulihan, penyesuaian emosi, dan kebutuhan dukungan jangka panjang.', categoryId:'survivorship', tags:['survivorship','follow-up'], keywords:['setelah terapi','pemantauan'], glossaryTerms:['Survivorship','Remisi','Rekurensi'], status:'published', readingTime:6, ...common(references.nciSurvivorship), relatedArticleIds:['article-palliative','article-nutrition'], relatedJourneyStage:'Setelah Terapi', body:blocks(['Jadwal pemantauan bersifat individual.','Keluhan baru tetap perlu disampaikan kepada tim kesehatan.','Pemulihan fisik dan emosi dapat membutuhkan waktu.'],'Rencana tindak lanjut',['Mintalah ringkasan terapi dan rencana tindak lanjut yang menjelaskan jadwal kontrol, pemeriksaan, gejala yang perlu dilaporkan, dan siapa yang dapat dihubungi.','Kekhawatiran tentang kekambuhan, pekerjaan, relasi, atau perubahan tubuh adalah hal yang dapat dibicarakan dengan tim perawatan atau layanan dukungan.']) }),
  article({ id:'article-future-immunotherapy', slug:'mengenal-imunoterapi-dasar', title:'Mengenal Imunoterapi: Naskah Editorial', excerpt:'Naskah awal untuk menjelaskan imunoterapi secara umum setelah referensi dan peninjau medis ditetapkan.', categoryId:'imunoterapi', tags:['immunotherapy'], keywords:['sistem imun'], glossaryTerms:['Imunoterapi'], status:'in_review', readingTime:4, references:[], relatedArticleIds:[], relatedJourneyStage:'Terapi', body:blocks(['Imunoterapi mencakup beberapa pendekatan.','Tidak semua kanker ditangani dengan imunoterapi.'],'Status naskah',['Konten ini belum dipublikasikan dan masih memerlukan pemeriksaan referensi serta tinjauan medis.']) }),
]
