import { references } from '@/content/references'
import { article, blocks, common } from './helpers'

export const treatmentArticles = [
  article({ id:'article-chemo', slug:'mengenal-kemoterapi', title:'Mengenal Kemoterapi', excerpt:'Kemoterapi adalah kelompok obat antikanker dengan tujuan dan jadwal yang disesuaikan untuk setiap situasi klinis.', categoryId:'kemoterapi', tags:['chemotherapy','treatment'], keywords:['terapi obat'], glossaryTerms:['Kemoterapi','ECOG'], status:'published', featured:true, readingTime:6, ...common(references.nciChemo), relatedArticleIds:['article-fever','article-nutrition'], relatedJourneyStage:'Terapi', body:blocks(['Tujuan kemoterapi dapat berbeda pada setiap pasien.','Efek samping bergantung pada obat dan kondisi individu.','Jangan mengubah obat pendamping tanpa berdiskusi dengan tim kesehatan.'],'Sebelum terapi',['Tim kesehatan menentukan apakah kemoterapi sesuai berdasarkan diagnosis, tujuan perawatan, hasil pemeriksaan, dan kondisi Anda. Artikel ini tidak memberikan pilihan regimen atau dosis.','Simpan nomor kontak unit perawatan dan tanyakan gejala mana yang harus segera dilaporkan.']) }),
  article({ id:'article-radiation', slug:'mengenal-radioterapi', title:'Mengenal Radioterapi', excerpt:'Radioterapi menggunakan radiasi terarah untuk menangani kanker atau meredakan gejala dalam konteks tertentu.', categoryId:'radioterapi', tags:['radiation','treatment'], keywords:['radiasi','simulasi'], glossaryTerms:['Radioterapi'], status:'published', readingTime:5, ...common(references.nciRadiation), relatedArticleIds:['article-chemo','article-nutrition'], relatedJourneyStage:'Terapi', body:blocks(['Radioterapi direncanakan secara individual.','Area dan jadwal terapi ditentukan oleh tim radiasi.','Keluhan selama terapi perlu dilaporkan agar dapat dinilai.'],'Perencanaan radioterapi',['Sebelum terapi, tim dapat melakukan simulasi untuk membantu menentukan posisi dan area perawatan. Proses berbeda sesuai lokasi dan tujuan terapi.','Efek samping biasanya berkaitan dengan area yang menerima radiasi. Ikuti petunjuk perawatan kulit dan nutrisi dari tim Anda.']) }),
  article({ id:'article-fever', slug:'demam-setelah-kemoterapi', title:'Demam Setelah Kemoterapi', excerpt:'Demam setelah kemoterapi dapat menjadi tanda infeksi dan memerlukan penilaian segera sesuai arahan tim perawatan.', categoryId:'efek-samping', tags:['chemotherapy','fever'], keywords:['infeksi','neutropenia'], glossaryTerms:['Neutropenia','Febrile Neutropenia'], status:'published', featured:true, readingTime:4, ...common(references.nciInfection), relatedArticleIds:['article-chemo','article-caregiver'], relatedJourneyStage:'Terapi', body:blocks(['Demam setelah kemoterapi dapat memerlukan pertolongan segera.','Gunakan batas suhu dan jalur kontak yang diberikan tim perawatan Anda.','Jangan menunda menghubungi fasilitas kesehatan untuk menunggu gejala membaik.'],'Mengapa demam penting',['Beberapa terapi dapat menurunkan kemampuan tubuh melawan infeksi. Karena itu, demam atau menggigil perlu dinilai berdasarkan instruksi khusus dari fasilitas tempat Anda dirawat.','Sebelum pulang, catat nomor yang dapat dihubungi di luar jam kerja dan lokasi layanan darurat yang direkomendasikan.'],'Segera hubungi tim perawatan atau layanan darurat bila mengalami demam sesuai batas yang diberikan tim Anda, sesak berat, penurunan kesadaran, atau perdarahan yang tidak terkontrol.') }),
  article({ id:'article-nutrition', slug:'nutrisi-selama-terapi-kanker', title:'Nutrisi Selama Terapi Kanker', excerpt:'Kebutuhan nutrisi dapat berubah selama terapi; dukungan perlu disesuaikan dengan keluhan, kondisi, dan anjuran tim kesehatan.', categoryId:'nutrisi', tags:['nutrition','treatment'], keywords:['makan','berat badan'], glossaryTerms:['ECOG'], status:'published', readingTime:6, ...common(references.nciNutrition), relatedArticleIds:['article-chemo','article-radiation'], relatedJourneyStage:'Terapi', body:blocks(['Tidak ada satu pola makan yang cocok untuk semua pasien.','Keluhan makan sebaiknya dilaporkan sejak dini.','Suplemen dapat berinteraksi dengan terapi dan perlu dibahas dengan tim kesehatan.'],'Menjaga asupan',['Perubahan nafsu makan, rasa, mual, nyeri menelan, atau gangguan pencernaan dapat memengaruhi asupan. Catat keluhan dan perubahan berat badan untuk dibicarakan saat konsultasi.','Ahli gizi klinis dapat membantu membuat strategi yang sesuai. Informasi ini tidak menggantikan penilaian nutrisi individual.']) }),
]
