import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useUser } from '@/context/UserContext'
import { journeyStages } from '@/data/journey'
import { ChecklistPreview, ConsultationQuestionsPreview, CurrentJourneyCard, DashboardHero, LearningProgress, LocalProfileCard, NextStepCard, PrivacyNotice, RecentActivity, SavedContentPreview } from '@/components/dashboard/DashboardComponents'
import { PatientOnboarding } from '@/components/onboarding/PatientOnboarding'
import type { PreferredTopic, UserRole } from '@/types/user'
import { FollowUpDashboardWidget } from '@/pages/followUp/FollowUpPages'
export default function PersonalDashboardPage() { const { profile, progress, recovered, updateProfile, updateProgress, addActivity } = useUser(); const navigate = useNavigate(); const [showOnboarding, setShowOnboarding] = useState(!profile.onboardingCompleted); const stage = journeyStages.find(item => item.id === progress.journeyStage); const checklist = progress.checklistProgress.consultation ?? []; const notifications = useMemo(() => { const items: string[] = []; if (checklist.length > 0 && checklist.length < 3) items.push('Checklist Anda dapat dilanjutkan saat siap.'); if (progress.selectedQuestions.length) items.push(`Anda menyimpan ${progress.selectedQuestions.length} pertanyaan untuk konsultasi.`); if (stage) items.push('Ada topik edukasi terkait tahap yang sedang Anda pelajari.'); return items }, [checklist.length, progress.selectedQuestions.length, stage]);
  const complete = (role: UserRole | undefined, journeyStage: string | undefined, preferredTopics: PreferredTopic[]) => { updateProfile({ role, preferredTopics, onboardingCompleted: true }); updateProgress({ journeyStage }); setShowOnboarding(false); addActivity('Memulai perjalanan belajar', journeyStage ? `/journey?stage=${journeyStage}` : '/journey') }
  return <div className='dashboard-page'><div className='dashboard-shell'>{recovered && <p className='recovery-message' role='status'>Sebagian data lokal tidak dapat dibaca dan telah dipulihkan.</p>}<DashboardHero name={profile.displayName} notifications={notifications}/><nav className='lentera-hub' aria-label='My Lentera'><a href='/care-center'>Rencana Bersama</a><a href='/today'>Hari Ini</a><a href='/follow-up'>Follow-up</a><a href='/calendar'>+ Jadwal</a><a href='/diary'>+ Gejala</a><a href='/questions'>+ Pertanyaan</a><a href='/medications'>+ Obat</a><a href='/visit-prep'>Persiapan konsultasi</a><a href='#journey'>Perjalanan Saya</a><a href='#saved'>Artikel Tersimpan</a><a href='/profile'>Pengaturan</a></nav><FollowUpDashboardWidget/><main className='dashboard-grid'><div className='dashboard-main' id='journey'><CurrentJourneyCard stage={stage} completed={progress.completedStages.length} onChange={id => { updateProgress({ journeyStage: id }); addActivity(`Memilih tahap: ${journeyStages.find(x => x.id === id)?.title}`, `/journey?stage=${id}`) }}/><section className='continue-strip'><div><span className='dash-kicker'>LANJUTKAN</span><strong>{progress.lastActivity?.label ?? 'Mulai dari perjalanan Anda'}</strong></div><button onClick={() => navigate(progress.lastActivity?.href ?? '/journey')}>Lanjutkan</button></section><NextStepCard stage={stage} onOpen={label => { addActivity(`Membaca: ${label}`, stage ? `/journey?stage=${stage.id}` : '/journey'); navigate(stage ? `/journey?stage=${stage.id}` : '/journey') }}/><RecentActivity items={progress.recentActivity}/></div><aside className='dashboard-side'><div id='checklist'><ChecklistPreview items={checklist} onToggle={item => { const next = checklist.includes(item) ? checklist.filter(x => x !== item) : [...checklist, item]; updateProgress({ checklistProgress: { ...progress.checklistProgress, consultation: next } }); addActivity(`Checklist konsultasi: ${next.length} dari 3 selesai`, '/prepare') }}/></div><div id='questions'><ConsultationQuestionsPreview questions={progress.selectedQuestions} onAdd={question => { updateProgress({ selectedQuestions: [...progress.selectedQuestions, question] }); addActivity(`Menyimpan pertanyaan: ${question}`, '/questions') }}/></div><div id='saved'><SavedContentPreview articles={progress.savedArticles} terms={progress.savedGlossaryTerms}/></div><LearningProgress data={progress.learning} quizCount={Object.keys(progress.quizProgress).length}/><LocalProfileCard name={profile.displayName} role={profile.role}/></aside></main><PrivacyNotice/></div>{showOnboarding && <PatientOnboarding onComplete={complete} onSkip={() => { updateProfile({ onboardingCompleted: true }); setShowOnboarding(false) }}/>}</div> }
