import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useUser } from '@/context/UserContext'
import { clearCompanionData } from '@/hooks/useCompanionData'
import { PersonalPage } from './ProfilePage'
export default function PrivacyCenterPage(){
 const {reset,download}=useUser();const [confirmOpen,setConfirm]=useState(false);const navigate=useNavigate()
 const erase=(modules:('events'|'symptoms'|'medications'|'logs'|'daily')[])=>{if(confirm('Hapus data modul ini dari perangkat?')){clearCompanionData(modules);location.reload()}}
 return <PersonalPage eyebrow='PUSAT PRIVASI' title='Data Anda tetap dekat dengan Anda.' lead='Tanpa akun, data pendamping disimpan hanya di perangkat. Pengguna masuk dapat menyimpan data secara privat di backend Lentera.'><div className='privacy-grid'><section><h2>Yang disimpan</h2><ul><li>Jadwal, checklist, diary gejala, serta daftar obat yang Anda masukkan</li><li>Catatan harian dan penanda pengingat</li><li>Progres belajar, pertanyaan, dan item tersimpan</li></ul></section><section><h2>Batas penggunaan</h2><ul><li>Lentera tidak meminta nomor rekam medis atau identitas nasional</li><li>Data pendamping tidak dikirim sebagai isi analytics</li><li>Tidak ada tautan publik untuk membagikan data pribadi</li></ul></section></div><section className='privacy-explain'><h2>Di mana data berada?</h2><p>Tanpa akun, data berada di localStorage browser ini. Menghapus data browser juga dapat menghapus catatan. Untuk pengguna yang masuk, tabel pendamping dilindungi kebijakan akses per pengguna. Lentera tidak ditujukan sebagai pengganti rekam medis resmi fasilitas kesehatan.</p><h2>Kontrol data pendamping</h2><button onClick={()=>erase(['symptoms'])}>Hapus diary</button><button onClick={()=>erase(['medications','logs'])}>Hapus daftar obat</button><button onClick={()=>erase(['events'])}>Hapus kalender</button><button className='danger-link' onClick={()=>erase(['events','symptoms','medications','logs','daily'])}>Hapus semua data pendamping</button><hr/><button onClick={download}>Unduh Data Edukasi Saya</button><button className='danger-link' onClick={()=>setConfirm(true)}>Hapus Semua Data di Perangkat Ini</button>{confirmOpen&&<div className='confirm-box' role='alertdialog' aria-labelledby='privacy-delete'><h3 id='privacy-delete'>Hapus semua data lokal?</h3><p>Tindakan ini menghapus progres edukasi dan data pendamping dari perangkat ini.</p><button onClick={()=>setConfirm(false)}>Batal</button><button className='danger' onClick={()=>{clearCompanionData();reset();navigate('/')}}>Hapus Data</button></div>}</section></PersonalPage>
}
