import { Link } from 'react-router-dom'
import { ArrowRight, Bell, Bookmark, Check, ChevronRight, CircleUserRound, LockKeyhole } from 'lucide-react'
import { journeyStages, type JourneyStage } from '@/data/journey'
import type { ActivityItem, LearningProgress as LearningProgressData } from '@/types/user'

export function DashboardHero({ name, notifications }: { name?: string; notifications: string[] }) { return <header className='dash-hero'><div><span className='dash-kicker'>MY LENTERA</span><h1>Selamat datang kembali{name ? `, ${name}` : ''}.</h1><p>Lanjutkan dari bagian terakhir perjalanan Anda. Pelajari dengan tenang, saat Anda siap.</p></div><details className='notification-center'><summary aria-label={`${notifications.length} pengingat edukasi`}><Bell/><span>{notifications.length}</span></summary><div><strong>Pengingat lokal</strong>{notifications.map(item => <p key={item}>{item}</p>)}</div></details></header> }
export function CurrentJourneyCard({ stage, completed, onChange }: { stage?: JourneyStage; completed: number; onChange: (id: string) => void }) { const pct = Math.round(completed / journeyStages.length * 100); return <section className='dash-card journey-current'><span className='dash-kicker'>PERJALANAN ANDA SAAT INI</span><h2>{stage?.title ?? 'Pilih tahap perjalanan Anda'}</h2><p>{stage?.shortDescription ?? 'Pilihan ini selalu dapat diubah dan tidak disimpulkan dari gejala.'}</p>{stage && <><div className='journey-next'><small>TOPIK EDUKASI BERIKUTNYA</small><strong>{stage.relatedContent[0]}</strong></div><div className='progress-label'><span>Progres perjalanan</span><span>{pct}%</span></div><progress aria-label='Progres perjalanan' max='100' value={pct}/></>}<label className='stage-select'>Ubah tahap secara manual<select aria-label='Tahap perjalanan saat ini' value={stage?.id ?? ''} onChange={event => onChange(event.target.value)}><option value='' disabled>Pilih tahap</option>{journeyStages.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><Link className='dash-action primary' to={stage ? `/journey?stage=${stage.id}` : '/journey'}>Lanjutkan Perjalanan <ArrowRight/></Link></section> }
export function NextStepCard({ stage, onOpen }: { stage?: JourneyStage; onOpen: (label: string) => void }) { return <section className='dash-card'><span className='dash-kicker'>REKOMENDASI EDUKASI · BUKAN SARAN MEDIS</span><h2>Langkah belajar berikutnya</h2><p>Topik edukasi yang mungkin relevan untuk tahap yang Anda pilih.</p><ol className='next-list'>{(stage?.relatedContent ?? ['Kenali alur perjalanan', 'Siapkan pertanyaan konsultasi']).slice(0, 4).map((item, i) => <li key={item}><button onClick={() => onOpen(item)}><span>0{i + 1}</span>{item}<ChevronRight/></button></li>)}</ol></section> }
export function LearningProgress({ data, quizCount }: { data: LearningProgressData; quizCount: number }) { const rows = [['Diagnosis', data.diagnosis], ['Terapi', data.treatment], ['Caregiver', data.caregiver], ['Survivorship', data.survivorship]] as const; return <section className='dash-card progress-module' id='progress'><span className='dash-kicker'>PROGRES BELAJAR</span><h2>Belajar sesuai ritme Anda</h2>{rows.map(([label, value]) => <div key={label}><label><span>{label}</span><strong>{value}%</strong></label><progress aria-label={`Progres ${label}`} max='100' value={value}/></div>)}<footer><span>{data.glossaryViewed} istilah dilihat</span><span>{quizCount} kuis selesai</span></footer></section> }
export function DashboardEmptyState({ text, action, to }: { text: string; action: string; to: string }) { return <div className='dash-empty'><p>{text}</p><Link to={to}>{action} <ArrowRight/></Link></div> }
export function SavedContentPreview({ articles, terms }: { articles: string[]; terms: string[] }) { const items = [...articles.map(x => `Artikel: ${x}`), ...terms.map(x => `Istilah: ${x}`)]; return <Preview title='Tersimpan' icon={<Bookmark/>} items={items} empty={<DashboardEmptyState text='Belum ada artikel atau istilah tersimpan.' action='Jelajahi Artikel' to='/edukasi'/>}/> }
export function ConsultationQuestionsPreview({ questions, onAdd }: { questions: string[]; onAdd: (question: string) => void }) { return <section className='dash-card compact-card'><header><CircleUserRound/><h2>Pertanyaan Saya</h2><span>{questions.length}</span></header>{questions.length ? <ul>{questions.slice(0, 3).map(x => <li key={x}>{x}</li>)}</ul> : <DashboardEmptyState text='Belum ada pertanyaan untuk konsultasi.' action='Buat Pertanyaan' to='/questions'/>}<form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const value = String(form.get('question') ?? '').trim(); if (value) { onAdd(value); event.currentTarget.reset() } }}><label className='sr-only' htmlFor='quick-question'>Pertanyaan baru</label><input id='quick-question' name='question' placeholder='Tulis pertanyaan singkat…'/><button aria-label='Simpan pertanyaan'><Check/></button></form></section> }
export function ChecklistPreview({ items, onToggle }: { items: string[]; onToggle: (item: string) => void }) { const tasks = ['Catat pertanyaan utama', 'Bawa hasil yang tersedia', 'Ajak pendamping bila perlu']; return <section className='dash-card compact-card'><header><Check/><h2>Checklist Saya</h2><span>{items.length}/{tasks.length}</span></header>{tasks.map(item => <label className='mini-check' key={item}><input type='checkbox' checked={items.includes(item)} onChange={() => onToggle(item)}/><span><Check/></span>{item}</label>)}<Link className='subtle-link' to='/prepare'>Pilih persiapan lain <ArrowRight/></Link></section> }
export function RecentActivity({ items }: { items: ActivityItem[] }) { return <section className='dash-card'><span className='dash-kicker'>AKTIVITAS TERBARU</span><h2>Lanjutkan dari terakhir kali</h2>{items.length ? <ul className='activity-list'>{items.slice(0, 7).map(item => <li key={item.id}><Link to={item.href}>{item.label}<ChevronRight/></Link></li>)}</ul> : <DashboardEmptyState text='Belum ada aktivitas. Mulai dari tahap yang paling relevan bagi Anda.' action='Mulai belajar' to='/journey'/>}</section> }
export function PrivacyNotice() { return <aside className='privacy-notice'><LockKeyhole/><div><strong>Privasi di perangkat Anda</strong><p>Profil dan progres disimpan hanya di browser ini, bukan diunggah ke server.</p></div><Link to='/privacy-center'>Kelola data</Link></aside> }
export function LocalProfileCard({ name, role }: { name?: string; role?: string }) { return <section className='dash-card profile-card'><CircleUserRound/><div><span className='dash-kicker'>PROFIL LOKAL</span><h2>{name || 'Profil opsional'}</h2><p>{role ? `Peran: ${role}` : 'Tambahkan preferensi tanpa data medis sensitif.'}</p></div><Link to='/profile'>Pengaturan <ArrowRight/></Link></section> }
function Preview({ title, icon, items, empty }: { title: string; icon: React.ReactNode; items: string[]; empty: React.ReactNode }) { return <section className='dash-card compact-card'><header>{icon}<h2>{title}</h2><span>{items.length}</span></header>{items.length ? <ul>{items.slice(0, 4).map(x => <li key={x}>{x}</li>)}</ul> : empty}</section> }
