import { useState, type FormEvent } from 'react'
import { AlertTriangle, CalendarDays, Check, ChevronRight, ClipboardCheck, Copy, HeartHandshake, LockKeyhole, MessageSquareText, Plus, Printer, ShieldCheck, Stethoscope, TicketCheck, Trash2, Users } from 'lucide-react'
import { toast } from '@/components/ui/use-toast'
import { localDate, useCompanionData } from '@/hooks/useCompanionData'
import { useCareCenterData } from '@/hooks/useCareCenterData'
import type { CareEpisode, CaregiverScope, VisitSummary } from '@/types/careCenter'

const tabs=['Rencana bersama','Caregiver','Gejala','Tiket layanan','Q&A terverifikasi','Check-in'] as const
type Tab=typeof tabs[number]
const scopes:CaregiverScope[]=['Jadwal','Checklist','Dokumen','Pengingat']

export default function CareCenterPage(){
  const [tab,setTab]=useState<Tab>('Rencana bersama')
  return <main className='care-center-page'><div className='care-center-shell'>
    <header className='care-center-hero'><div><span>RUANG PERAWATAN ANDA</span><h1>Pusat Rencana Perawatan Bersama</h1><p>Satukan persiapan, kunjungan, dan tindak lanjut dalam satu alur yang dapat dikerjakan bersama orang tepercaya.</p></div><div className='storage-badge'><LockKeyhole/><div><strong>Tersimpan di perangkat ini</strong><small>Data kesehatan tidak ikut sinkronisasi edukasi.</small></div></div></header>
    <nav className='care-tabs' aria-label='Fitur pusat perawatan'>{tabs.map(item=><button key={item} aria-current={tab===item?'page':undefined} onClick={()=>setTab(item)}>{item}</button>)}</nav>
    {tab==='Rencana bersama'&&<SharedPlan/>}{tab==='Caregiver'&&<CaregiverMode/>}{tab==='Gejala'&&<SymptomTracker/>}{tab==='Tiket layanan'&&<TicketInbox/>}{tab==='Q&A terverifikasi'&&<VerifiedQA/>}{tab==='Check-in'&&<Wellbeing/>}
  </div></main>
}

function SharedPlan(){const data=useCareCenterData(),companion=useCompanionData();const [show,setShow]=useState(false);const [selected,setSelected]=useState<CareEpisode|null>(null);const episodes=[...data.episodes].sort((a,b)=>a.date.localeCompare(b.date));const save=(episode:CareEpisode)=>{data.setEpisodes(old=>old.some(x=>x.id===episode.id)?old.map(x=>x.id===episode.id?episode:x):[...old,episode]);setShow(false);setSelected(episode);toast.success('Episode perawatan tersimpan')};return <>
  <section className='care-overview'><div><span>RENCANA AKTIF</span><strong>{episodes.filter(x=>x.phase!=='selesai').length}</strong><small>episode perawatan</small></div><div><span>TUGAS TERBUKA</span><strong>{episodes.flatMap(x=>x.tasks).filter(x=>!x.done).length}</strong><small>perlu ditindaklanjuti</small></div><div><span>JADWAL TERHUBUNG</span><strong>{companion.events.length}</strong><small>dari kalender Anda</small></div></section>
  <div className='care-section-head'><div><span>SEBELUM · SAAT · SETELAH</span><h2>Episode perawatan</h2></div><button className='care-primary' onClick={()=>setShow(true)}><Plus/> Buat episode</button></div>
  {show&&<EpisodeForm events={companion.events} onCancel={()=>setShow(false)} onSave={save}/>} {!episodes.length&&<Empty icon={<CalendarDays/>} title='Belum ada episode perawatan' text='Buat dari jadwal yang sudah ada atau mulai rencana baru.'/ >}
  <div className='episode-grid'>{episodes.map(ep=><EpisodeCard key={ep.id} episode={ep} active={selected?.id===ep.id} onOpen={()=>setSelected(ep)} onToggle={id=>data.setEpisodes(old=>old.map(x=>x.id===ep.id?{...x,tasks:x.tasks.map(t=>t.id===id?{...t,done:!t.done}:t)}:x))} onDelete={()=>confirm('Hapus episode ini?')&&data.setEpisodes(old=>old.filter(x=>x.id!==ep.id))}/>)}</div>
  {selected&&<EpisodeDetail episode={data.episodes.find(x=>x.id===selected.id)??selected} onSave={save}/>}</>}

function EpisodeForm({events,onCancel,onSave}:{events:{id:string;title:string;date:string;time?:string;location?:string;clinician?:string}[];onCancel:()=>void;onSave:(x:CareEpisode)=>void}){const [source,setSource]=useState('');const event=events.find(x=>x.id===source);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const task=String(d.get('task')).trim();onSave({id:crypto.randomUUID(),title:String(d.get('title')),date:String(d.get('date')),time:String(d.get('time')),location:String(d.get('location')),clinician:String(d.get('clinician')),phase:'persiapan',caregiver:String(d.get('caregiver')),reminder:String(d.get('reminder')),questions:[],documents:[],tasks:task?[{id:crypto.randomUUID(),title:task,owner:'Pasien',dueDate:String(d.get('date')),done:false}]:[],createdAt:new Date().toISOString()})};return <form className='care-form' onSubmit={submit}><header><div><span>EPISODE BARU</span><h2>Mulai dari jadwal atau rencana baru</h2></div><button type='button' onClick={onCancel}>Tutup</button></header><label className='wide'>Ambil dari kalender <select value={source} onChange={e=>setSource(e.target.value)}><option value=''>Mulai kosong</option>{events.map(x=><option key={x.id} value={x.id}>{x.date} · {x.title}</option>)}</select></label><div className='care-form-grid' key={source}><label>Nama kunjungan<input name='title' required defaultValue={event?.title}/></label><label>Tanggal<input name='date' type='date' required defaultValue={event?.date??localDate()}/></label><label>Waktu<input name='time' type='time' defaultValue={event?.time}/></label><label>Lokasi<input name='location' defaultValue={event?.location}/></label><label>Dokter / tenaga kesehatan<input name='clinician' defaultValue={event?.clinician}/></label><label>Caregiver<input name='caregiver' placeholder='Nama pendamping'/></label><label className='wide'>Pengingat penting<input name='reminder' placeholder='Contoh: puasa mulai pukul 22.00'/></label><label className='wide'>Tugas pertama<input name='task' placeholder='Contoh: bawa hasil laboratorium'/></label></div><footer><button type='button' onClick={onCancel}>Batal</button><button className='care-primary'>Simpan episode</button></footer></form>}

function EpisodeCard({episode,active,onOpen,onToggle,onDelete}:{episode:CareEpisode;active:boolean;onOpen:()=>void;onToggle:(id:string)=>void;onDelete:()=>void}){const open=episode.tasks.filter(x=>!x.done).length;return <article className={`episode-card ${active?'active':''}`}><button className='episode-open' onClick={onOpen}><span className={`phase ${episode.phase}`}>{episode.phase.replace('-',' ')}</span><time>{new Date(`${episode.date}T00:00`).toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})}</time><h3>{episode.title}</h3><p>{episode.location||'Lokasi belum dicatat'}{episode.caregiver?` · bersama ${episode.caregiver}`:''}</p><div><strong>{open}</strong> tugas belum selesai <ChevronRight/></div></button>{episode.tasks.slice(0,3).map(task=><label className='episode-task' key={task.id}><input type='checkbox' checked={task.done} onChange={()=>onToggle(task.id)}/><span>{task.title}<small>{task.owner}</small></span></label>)}<button className='delete-icon' aria-label={`Hapus ${episode.title}`} onClick={onDelete}><Trash2/></button></article>}

function EpisodeDetail({episode,onSave}:{episode:CareEpisode;onSave:(x:CareEpisode)=>void}){const [task,setTask]=useState(''),[question,setQuestion]=useState(''),[document,setDocument]=useState(''),[summary,setSummary]=useState(false);const update=(patch:Partial<CareEpisode>)=>onSave({...episode,...patch});const addTask=()=>{if(task.trim()){update({tasks:[...episode.tasks,{id:crypto.randomUUID(),title:task.trim(),owner:'Pasien',done:false}]});setTask('')}};return <section className='episode-detail'><header><div><span>RENCANA TERPILIH</span><h2>{episode.title}</h2></div><select aria-label='Fase episode' value={episode.phase} onChange={e=>update({phase:e.target.value as CareEpisode['phase']})}><option value='persiapan'>Persiapan</option><option value='kunjungan'>Hari kunjungan</option><option value='tindak-lanjut'>Tindak lanjut</option><option value='selesai'>Selesai</option></select></header><ol className='phase-rail'><li className='done'>Persiapan</li><li className={episode.phase!=='persiapan'?'done':''}>Kunjungan</li><li className={episode.phase==='tindak-lanjut'||episode.phase==='selesai'?'done':''}>Tindak lanjut</li></ol><div className='episode-columns'><EditorList title='Tugas bersama' items={episode.tasks.map(x=>x.title)} value={task} setValue={setTask} add={addTask}/><EditorList title='Pertanyaan untuk dokter' items={episode.questions} value={question} setValue={setQuestion} add={()=>{if(question.trim()){update({questions:[...episode.questions,question.trim()]});setQuestion('')}}}/><EditorList title='Dokumen yang dibawa' items={episode.documents} value={document} setValue={setDocument} add={()=>{if(document.trim()){update({documents:[...episode.documents,document.trim()]});setDocument('')}}}/></div><div className='episode-actions'><button onClick={()=>setSummary(true)}><ClipboardCheck/> Isi ringkasan kunjungan</button><button onClick={()=>window.print()}><Printer/> Cetak paket</button><button onClick={()=>copySummary(episode)}><Copy/> Salin ringkasan terbatas</button></div>{summary&&<VisitForm current={episode.visitNote} onSave={note=>{update({visitNote:note,phase:'tindak-lanjut',date:note.nextVisitDate||episode.date,tasks:[...episode.tasks,...note.followUpTasks.split('\n').filter(Boolean).map(title=>({id:crypto.randomUUID(),title,owner:'Pasien' as const,done:false}))]});setSummary(false)}}/>}<PrintPack episode={episode}/></section>}
function EditorList({title,items,value,setValue,add}:{title:string;items:string[];value:string;setValue:(x:string)=>void;add:()=>void}){return <section><h3>{title}</h3>{items.length?<ul>{items.map((x,i)=><li key={`${x}-${i}`}><Check/>{x}</li>)}</ul>:<p>Belum ada item.</p>}<div><input aria-label={`Tambah ${title}`} value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add()}}}/><button onClick={add}>Tambah</button></div></section>}
function VisitForm({current,onSave}:{current?:VisitSummary;onSave:(x:VisitSummary)=>void}){const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);onSave({decision:String(d.get('decision')),therapyChange:String(d.get('therapyChange')),requestedTests:String(d.get('requestedTests')),nextVisitDate:String(d.get('nextVisitDate')),followUpTasks:String(d.get('followUpTasks')),symptomsToWatch:String(d.get('symptomsToWatch'))})};return <form className='visit-summary-form' onSubmit={submit}><h3>Ringkasan setelah kunjungan</h3><p>Tulis kembali informasi yang Anda terima. Lentera tidak menafsirkan keputusan klinis.</p><label>Keputusan tenaga kesehatan<textarea name='decision' required defaultValue={current?.decision}/></label><label>Perubahan terapi<textarea name='therapyChange' defaultValue={current?.therapyChange}/></label><label>Pemeriksaan yang diminta<textarea name='requestedTests' defaultValue={current?.requestedTests}/></label><label>Kontrol berikutnya<input name='nextVisitDate' type='date' defaultValue={current?.nextVisitDate}/></label><label>Tugas tindak lanjut <small>satu per baris</small><textarea name='followUpTasks' defaultValue={current?.followUpTasks}/></label><label>Hal yang diminta untuk dipantau<textarea name='symptomsToWatch' defaultValue={current?.symptomsToWatch}/></label><button className='care-primary'>Simpan dan masuk tindak lanjut</button></form>}
function PrintPack({episode}:{episode:CareEpisode}){return <article className='care-print-pack'><h1>{episode.title}</h1><p>{episode.date} · {episode.time||'Waktu belum dicatat'} · {episode.location||'Lokasi belum dicatat'}</p><h2>Checklist</h2><ul>{episode.tasks.map(x=><li key={x.id}>{x.done?'✓':'□'} {x.title} — {x.owner}</li>)}</ul><h2>Pertanyaan</h2><ul>{episode.questions.map(x=><li key={x}>{x}</li>)}</ul><h2>Dokumen</h2><ul>{episode.documents.map(x=><li key={x}>{x}</li>)}</ul><p className='print-note'>Ringkasan ini berasal dari input pengguna dan bukan dokumen medis resmi.</p></article>}
function copySummary(e:CareEpisode){const text=`${e.title}\n${e.date} ${e.time||''}\n${e.location||''}\n\nTugas:\n${e.tasks.map(x=>`- ${x.title} (${x.owner})`).join('\n')}\n\nPertanyaan:\n${e.questions.map(x=>`- ${x}`).join('\n')}\n\nDokumen:\n${e.documents.map(x=>`- ${x}`).join('\n')}`;navigator.clipboard?.writeText(text).then(()=>toast.success('Ringkasan terbatas disalin')).catch(()=>toast.error('Tidak dapat menyalin ringkasan'))}

function CaregiverMode(){const data=useCareCenterData();const [show,setShow]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const selected=scopes.filter(x=>d.get(x)==='on');data.setCaregivers(old=>[...old,{id:crypto.randomUUID(),name:String(d.get('name')),contact:String(d.get('contact')),scopes:selected,expiresAt:String(d.get('expires')),consented:d.get('consent')==='on',activity:[`Undangan dibuat ${new Date().toLocaleString('id-ID')}`]}]);setShow(false);toast.success('Undangan caregiver dibuat')};return <section><SectionTitle icon={<Users/>} eyebrow='AKSES TERBATAS' title='Delegasi caregiver' text='Berikan hanya akses yang diperlukan, dengan persetujuan dan tanggal kedaluwarsa.'/><button className='care-primary' onClick={()=>setShow(v=>!v)}><Plus/> Undang caregiver</button>{show&&<form className='care-form compact' onSubmit={submit}><div className='care-form-grid'><label>Nama<input name='name' required/></label><label>Email atau nomor telepon<input name='contact' required/></label><label>Akses berakhir<input name='expires' type='date' required/></label><fieldset className='wide'><legend>Izin yang diberikan</legend>{scopes.map(x=><label key={x}><input name={x} type='checkbox'/>{x}</label>)}</fieldset><label className='wide consent'><input name='consent' type='checkbox' required/> Saya memahami data apa yang akan dapat diakses.</label></div><button className='care-primary'>Buat undangan</button></form>}<div className='access-grid'>{data.caregivers.map(x=><article className='access-card' key={x.id}><div><HeartHandshake/><span>{x.revokedAt?'DICABUT':'AKTIF SAMPAI '+x.expiresAt}</span></div><h3>{x.name}</h3><p>{x.contact}</p><ul>{x.scopes.map(s=><li key={s}><Check/>{s}</li>)}</ul><details><summary>Riwayat aktivitas</summary>{x.activity.map(a=><p key={a}>{a}</p>)}</details>{!x.revokedAt&&<button onClick={()=>data.setCaregivers(old=>old.map(c=>c.id===x.id?{...c,revokedAt:new Date().toISOString(),activity:[...c.activity,'Akses dicabut oleh pasien']}:c))}>Cabut akses</button>}</article>)}</div>{!data.caregivers.length&&<Empty icon={<HeartHandshake/>} title='Belum ada caregiver' text='Anda tetap memegang kendali penuh atas akses.'/ >}</section>}

function SymptomTracker(){const companion=useCompanionData();const [score,setScore]=useState(1),[symptom,setSymptom]=useState(''),[change,setChange]=useState('Sama'),[contacted,setContacted]=useState(false);const danger=score>=8||/sesak|perdarahan|pingsan|demam/i.test(symptom);const save=(e:FormEvent)=>{e.preventDefault();companion.setSymptoms(old=>[{id:crypto.randomUUID(),date:localDate(),symptom,severity:score<=3?'mild':score<=6?'moderate':'severe',duration:`Skor gangguan ${score}/10 · ${change} dari kemarin`,action:contacted?'Sudah menghubungi tenaga kesehatan':'Belum menghubungi tenaga kesehatan'},...old]);setSymptom('');toast.success('Catatan gejala tersimpan di perangkat ini')};return <section><SectionTitle icon={<Stethoscope/>} eyebrow='CATATAN, BUKAN DIAGNOSIS' title='Pelacak gejala ringan' text='Catat perubahan dari waktu ke waktu untuk membantu percakapan dengan tenaga kesehatan.'/>{danger&&<div className='danger-notice' role='alert'><AlertTriangle/><div><strong>Jangan menunggu penilaian dari aplikasi</strong><p>Jika gejala terasa gawat, memburuk cepat, atau Anda khawatir, hubungi fasilitas kesehatan atau layanan darurat setempat sekarang.</p></div></div>}<form className='symptom-check' onSubmit={save}><label>Gejala yang dirasakan<input value={symptom} onChange={e=>setSymptom(e.target.value)} required placeholder='Gunakan kata-kata Anda sendiri'/></label><label>Seberapa mengganggu? <strong>{score}/10</strong><input type='range' min='0' max='10' value={score} onChange={e=>setScore(Number(e.target.value))}/></label><label>Perubahan sejak kemarin<select value={change} onChange={e=>setChange(e.target.value)}><option>Membaik</option><option>Sama</option><option>Memburuk</option></select></label><label className='consent'><input type='checkbox' checked={contacted} onChange={e=>setContacted(e.target.checked)}/> Saya sudah menghubungi tenaga kesehatan</label><button className='care-primary'>Simpan catatan</button></form><div className='symptom-trend'><h3>Catatan terbaru</h3>{companion.symptoms.slice(0,8).map(x=><article key={x.id}><time>{x.date}</time><strong>{x.symptom}</strong><span className={x.severity}>{x.severity==='mild'?'Ringan':x.severity==='moderate'?'Sedang':'Berat'}</span><p>{x.duration}</p></article>)}</div><p className='clinical-boundary'><ShieldCheck/> Lentera tidak menentukan penyebab, kegawatan, diagnosis, atau perubahan dosis obat.</p></section>}

function TicketInbox(){const data=useCareCenterData();const [show,setShow]=useState(false);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),n=`LNT-${new Date().getFullYear()}-${String(data.tickets.length+1).padStart(4,'0')}`;data.setTickets(old=>[{id:crypto.randomUUID(),number:n,category:String(d.get('category')),subject:String(d.get('subject')),message:String(d.get('message')),status:'Baru',createdAt:new Date().toISOString(),sla:'Respons awal maksimal 2 hari kerja',history:['Tiket diterima']},...old]);setShow(false);toast.success(`Tiket ${n} dibuat`)};return <section><SectionTitle icon={<TicketCheck/>} eyebrow='ADMINISTRASI & LAYANAN' title='Kotak masuk berbasis tiket' text='Pantau status permintaan tanpa menggunakan kanal ini untuk kondisi medis mendesak.'/><div className='service-warning'><AlertTriangle/> Bukan kanal kegawatdaruratan atau konsultasi medis.</div><button className='care-primary' onClick={()=>setShow(v=>!v)}><Plus/> Buat tiket</button>{show&&<form className='care-form compact' onSubmit={submit}><div className='care-form-grid'><label>Kategori<select name='category'><option>Administrasi</option><option>Jadwal layanan</option><option>Fasilitas</option><option>Akses informasi</option></select></label><label>Subjek<input name='subject' required/></label><label className='wide'>Pesan<textarea name='message' required/></label></div><button className='care-primary'>Kirim permintaan</button></form>}<div className='ticket-list'>{data.tickets.map(x=><article key={x.id}><div><span>{x.number}</span><strong>{x.status}</strong></div><h3>{x.subject}</h3><p>{x.category} · {x.sla}</p><details><summary>Lihat riwayat</summary>{x.history.map(h=><p key={h}>{h}</p>)}</details></article>)}</div>{!data.tickets.length&&<Empty icon={<TicketCheck/>} title='Belum ada tiket' text='Permintaan administratif Anda akan muncul di sini.'/ >}</section>}

function VerifiedQA(){const data=useCareCenterData();const [question,setQuestion]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();data.setQuestions(old=>[{id:crypto.randomUUID(),question,status:'Dikirim'},...old]);setQuestion('');toast.success('Pertanyaan dikirim untuk ditinjau')};return <section><SectionTitle icon={<MessageSquareText/>} eyebrow='MODERASI MEDIS' title='Q&A terverifikasi' text='Ajukan pertanyaan umum. Jangan sertakan identitas, hasil pemeriksaan, atau detail diagnosis.'/><form className='qa-ask' onSubmit={submit}><textarea value={question} onChange={e=>setQuestion(e.target.value)} required placeholder='Apa yang ingin Anda pahami secara umum?'/><button className='care-primary'>Kirim pertanyaan</button></form><div className='qa-list'>{data.questions.map(x=><article key={x.id}><span>{x.status}</span><h3>{x.question}</h3>{x.answer?<><p>{x.answer}</p><small><ShieldCheck/> Ditinjau {x.reviewedBy} · {x.reviewedAt}</small></>:<p>Tim editorial akan menggabungkan pertanyaan serupa dan menautkannya ke artikel bila tersedia.</p>}{x.article&&<a href={x.article}>Baca artikel terkait</a>}</article>)}</div>{!data.questions.length&&<Empty icon={<MessageSquareText/>} title='Belum ada pertanyaan' text='Jawaban terverifikasi akan menampilkan reviewer dan tanggal review.'/ >}</section>}

function Wellbeing(){const data=useCareCenterData();const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);data.setCheckins(old=>[{id:crypto.randomUUID(),date:localDate(),feeling:String(d.get('feeling')),transport:d.get('transport')==='on',companion:d.get('companion')==='on',understanding:d.get('understanding')==='on',callback:d.get('callback')==='on',consent:d.get('consent')==='on'},...old]);e.currentTarget.reset();toast.success('Check-in tersimpan')};return <section><SectionTitle icon={<HeartHandshake/>} eyebrow='KEBUTUHAN NONMEDIS' title='Check-in mingguan' text='Bantu identifikasi hambatan akses dan dukungan—bukan untuk menilai kondisi penyakit.'/><form className='wellbeing-form' onSubmit={submit}><fieldset><legend>Bagaimana kondisi Anda minggu ini?</legend>{['Baik','Cukup','Berat'].map(x=><label key={x}><input type='radio' name='feeling' value={x} required/>{x}</label>)}</fieldset><label><input name='transport' type='checkbox'/> Saya mengalami kesulitan transportasi</label><label><input name='companion' type='checkbox'/> Saya membutuhkan pendamping</label><label><input name='understanding' type='checkbox'/> Saya kesulitan memahami instruksi</label><label><input name='callback' type='checkbox'/> Saya ingin dihubungi petugas</label><label className='consent'><input name='consent' type='checkbox' required/> Saya setuju jawaban ini digunakan untuk tindak lanjut layanan.</label><button className='care-primary'>Simpan check-in</button></form>{data.checkins[0]&&<div className='last-checkin'><Check/><div><strong>Check-in terakhir: {data.checkins[0].date}</strong><p>{data.checkins[0].callback?'Anda meminta dihubungi petugas.':'Tidak ada permintaan untuk dihubungi.'}</p></div></div>}</section>}

function SectionTitle({icon,eyebrow,title,text}:{icon:React.ReactNode;eyebrow:string;title:string;text:string}){return <header className='feature-heading'><div>{icon}</div><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></header>}
function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className='care-empty'>{icon}<h3>{title}</h3><p>{text}</p></div>}
