create extension if not exists pgcrypto;
create type public.app_role as enum ('learner','patient','caregiver','survivor','editor','medical_reviewer','admin');
create type public.article_status as enum ('draft','in_review','revision_required','approved','published','archived');
create type public.saved_item_type as enum ('article','glossary','journey','checklist');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text check(char_length(display_name)<=100), role public.app_role not null default 'learner', editorial_enabled boolean not null default true, sync_enabled boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, description text not null default '', icon text, sort_order integer not null default 0, active boolean not null default true);
create table public.articles (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null default '', subtitle text, excerpt text not null default '', status public.article_status not null default 'draft', category_id uuid references public.categories, featured boolean not null default false, body jsonb not null default '[]' check(jsonb_typeof(body)='array'), author_id uuid references public.profiles, reviewer_id uuid references public.profiles, requires_medical_review boolean not null default true, editorial_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), published_at timestamptz, last_reviewed_at timestamptz, next_review_at timestamptz, seo_title text, seo_description text);
create table public.article_references (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.articles on delete cascade, title text not null, authors text, journal text, year integer check(year between 1800 and 2200), doi text, url text, source_type text not null check(source_type in ('guideline','journal','systematic_review','government','organization','textbook')), sort_order integer not null default 0);
create table public.article_revisions (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.articles on delete cascade, version integer not null, summary text not null, body_snapshot jsonb not null, changed_by uuid references public.profiles, created_at timestamptz not null default now(), unique(article_id,version));
create table public.editorial_comments (id uuid primary key default gen_random_uuid(), article_id uuid not null references public.articles on delete cascade, author_id uuid not null references public.profiles, parent_id uuid references public.editorial_comments on delete cascade, comment text not null check(char_length(trim(comment)) between 1 and 5000), resolved boolean not null default false, created_at timestamptz not null default now(), resolved_at timestamptz, resolved_by uuid references public.profiles);
create table public.tags (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null);
create table public.article_tags (article_id uuid references public.articles on delete cascade, tag_id uuid references public.tags on delete cascade, primary key(article_id,tag_id));
create table public.saved_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, item_type public.saved_item_type not null, item_id text not null, created_at timestamptz not null default now(), unique(user_id,item_type,item_id));
create table public.learning_progress (user_id uuid primary key references public.profiles on delete cascade, journey_stage text, completed_stages jsonb not null default '[]', glossary_terms jsonb not null default '[]', quiz_progress jsonb not null default '{}', checklist_progress jsonb not null default '{}', updated_at timestamptz not null default now());
create table public.consultation_questions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, question text not null check(char_length(trim(question)) between 1 and 1000), category text, selected boolean not null default true, custom boolean not null default false, created_at timestamptz not null default now());
create table public.audit_logs (id bigint generated always as identity primary key, actor_id uuid references auth.users on delete set null, action text not null check(action in ('article_created','article_updated','submitted_for_review','revision_requested','review_approved','article_published','article_archived','reviewer_assigned','role_changed')), target_type text not null, target_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());

create index articles_status_idx on public.articles(status); create index articles_category_idx on public.articles(category_id); create index articles_updated_idx on public.articles(updated_at desc); create index saved_user_idx on public.saved_items(user_id); create index audit_created_idx on public.audit_logs(created_at desc); create index comments_article_idx on public.editorial_comments(article_id);

create or replace function public.has_role(required_role text) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from public.profiles where id=auth.uid() and role::text=required_role and editorial_enabled) $$;
create or replace function public.is_editorial() returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in ('editor','medical_reviewer','admin') and editorial_enabled) $$;
revoke all on function public.has_role(text) from public; grant execute on function public.has_role(text) to authenticated, anon;
revoke all on function public.is_editorial() from public; grant execute on function public.is_editorial() to authenticated;

create or replace function public.new_user_profile() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ begin insert into public.profiles(id,display_name,role) values(new.id, nullif(new.raw_user_meta_data->>'display_name',''), case when new.raw_user_meta_data->>'relationship' in ('learner','patient','caregiver','survivor') then (new.raw_user_meta_data->>'relationship')::public.app_role else 'learner' end); return new; end $$;
create trigger auth_user_profile after insert on auth.users for each row execute function public.new_user_profile();
create or replace function public.prevent_role_escalation() returns trigger language plpgsql set search_path=public,pg_temp as $$ begin if new.role<>old.role or new.editorial_enabled<>old.editorial_enabled then if not public.has_role('admin') then raise exception 'role changes require admin'; end if; end if; new.updated_at=now(); return new; end $$;
create trigger profiles_role_guard before update on public.profiles for each row execute function public.prevent_role_escalation();

create or replace function public.article_transition(article uuid, requested public.article_status, note text default null) returns public.articles language plpgsql security definer set search_path=public,pg_temp as $$ declare a public.articles; action_name text; begin select * into a from public.articles where id=article for update; if a.id is null then raise exception 'article not found'; end if;
if requested='in_review' and a.status in ('draft','revision_required') and (a.author_id=auth.uid() or public.has_role('admin')) then action_name='submitted_for_review';
elsif requested='revision_required' and a.status='in_review' and a.reviewer_id=auth.uid() and nullif(trim(note),'') is not null then action_name='revision_requested';
elsif requested='approved' and a.status='in_review' and a.reviewer_id=auth.uid() then action_name='review_approved';
elsif requested='published' and a.status='approved' and public.has_role('admin') then if trim(a.title)='' or trim(a.excerpt)='' or a.category_id is null or jsonb_array_length(a.body)=0 or trim(coalesce(a.seo_description,''))='' or (a.requires_medical_review and a.reviewer_id is null) then raise exception 'publishing requirements not met'; end if; action_name='article_published';
elsif requested='archived' and a.status='published' and public.has_role('admin') then action_name='article_archived'; else raise exception 'transition not permitted'; end if;
update public.articles set status=requested, updated_at=now(), published_at=case when requested='published' then now() else published_at end, last_reviewed_at=case when requested='approved' then now() else last_reviewed_at end where id=article returning * into a;
if requested='revision_required' then insert into public.editorial_comments(article_id,author_id,comment) values(article,auth.uid(),trim(note)); end if; insert into public.audit_logs(actor_id,action,target_type,target_id) values(auth.uid(),action_name,'article',article); return a; end $$;
revoke all on function public.article_transition(uuid,public.article_status,text) from public; grant execute on function public.article_transition(uuid,public.article_status,text) to authenticated;

alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.articles enable row level security; alter table public.article_references enable row level security; alter table public.article_revisions enable row level security; alter table public.editorial_comments enable row level security; alter table public.tags enable row level security; alter table public.article_tags enable row level security; alter table public.saved_items enable row level security; alter table public.learning_progress enable row level security; alter table public.consultation_questions enable row level security; alter table public.audit_logs enable row level security;
create policy profiles_own_read on public.profiles for select using(id=auth.uid() or (public.has_role('admin') and role in ('editor','medical_reviewer','admin')));
create policy profiles_own_update on public.profiles for update using(id=auth.uid() or public.has_role('admin')) with check(id=auth.uid() or public.has_role('admin'));
create policy categories_public_read on public.categories for select using(active or public.is_editorial()); create policy categories_admin_write on public.categories for all using(public.has_role('admin')) with check(public.has_role('admin'));
create policy articles_public_or_editorial_read on public.articles for select using(status='published' or public.has_role('admin') or (public.has_role('editor') and author_id=auth.uid()) or (public.has_role('medical_reviewer') and reviewer_id=auth.uid()));
create policy articles_editor_insert on public.articles for insert with check((public.has_role('editor') and author_id=auth.uid() and status='draft') or public.has_role('admin'));
create policy articles_editor_update on public.articles for update using((public.has_role('editor') and author_id=auth.uid() and status in ('draft','revision_required')) or public.has_role('admin')) with check((public.has_role('editor') and author_id=auth.uid() and status in ('draft','revision_required')) or public.has_role('admin'));
create policy references_read on public.article_references for select using(exists(select 1 from public.articles a where a.id=article_id)); create policy references_editor_write on public.article_references for all using(exists(select 1 from public.articles a where a.id=article_id and ((a.author_id=auth.uid() and public.has_role('editor') and a.status in ('draft','revision_required')) or public.has_role('admin'))));
create policy revisions_editorial_read on public.article_revisions for select using(public.is_editorial()); create policy revisions_author_insert on public.article_revisions for insert with check(changed_by=auth.uid() and exists(select 1 from public.articles a where a.id=article_id and (a.author_id=auth.uid() or public.has_role('admin'))));
create policy comments_participant_read on public.editorial_comments for select using(exists(select 1 from public.articles a where a.id=article_id and (a.author_id=auth.uid() or a.reviewer_id=auth.uid() or public.has_role('admin')))); create policy comments_participant_insert on public.editorial_comments for insert with check(author_id=auth.uid() and exists(select 1 from public.articles a where a.id=article_id and (a.author_id=auth.uid() or a.reviewer_id=auth.uid() or public.has_role('admin'))));
create policy tags_read on public.tags for select using(true); create policy tags_admin_write on public.tags for all using(public.has_role('admin')); create policy article_tags_read on public.article_tags for select using(true); create policy article_tags_editor_write on public.article_tags for all using(public.is_editorial());
create policy saved_own on public.saved_items for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy progress_own on public.learning_progress for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy questions_own on public.consultation_questions for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy audit_admin_read on public.audit_logs for select using(public.has_role('admin'));

create or replace function public.audit_article_change() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ begin insert into public.audit_logs(actor_id,action,target_type,target_id,metadata) values(auth.uid(),case when tg_op='INSERT' then 'article_created' else 'article_updated' end,'article',new.id,jsonb_build_object('status',new.status)); return new; end $$;
create trigger articles_audit after insert or update on public.articles for each row execute function public.audit_article_change();
-- Status is mutable only through the validated workflow RPC, including for admins.
create or replace function public.guard_article_status() returns trigger language plpgsql set search_path=public,pg_temp as $$ begin if new.status<>old.status and coalesce(current_setting('app.workflow_transition',true),'')<>'allowed' then raise exception 'use article_transition'; end if; return new; end $$;
create trigger articles_status_guard before update of status on public.articles for each row execute function public.guard_article_status();
create or replace function public.article_transition(article uuid, requested public.article_status, note text default null) returns public.articles language plpgsql security definer set search_path=public,pg_temp as $$ declare a public.articles; action_name text; begin select * into a from public.articles where id=article for update; if a.id is null then raise exception 'article not found'; end if;
if requested='in_review' and a.status in ('draft','revision_required') and (a.author_id=auth.uid() or public.has_role('admin')) then action_name='submitted_for_review';
elsif requested='revision_required' and a.status='in_review' and a.reviewer_id=auth.uid() and nullif(trim(note),'') is not null then action_name='revision_requested';
elsif requested='approved' and a.status='in_review' and a.reviewer_id=auth.uid() then action_name='review_approved';
elsif requested='published' and a.status='approved' and public.has_role('admin') then if trim(a.title)='' or trim(a.excerpt)='' or a.category_id is null or jsonb_array_length(a.body)=0 or trim(coalesce(a.seo_description,''))='' or (a.requires_medical_review and a.reviewer_id is null) then raise exception 'publishing requirements not met'; end if; action_name='article_published';
elsif requested='archived' and a.status='published' and public.has_role('admin') then action_name='article_archived'; else raise exception 'transition not permitted'; end if;
perform set_config('app.workflow_transition','allowed',true); update public.articles set status=requested, updated_at=now(), published_at=case when requested='published' then now() else published_at end, last_reviewed_at=case when requested='approved' then now() else last_reviewed_at end where id=article returning * into a;
if requested='revision_required' then insert into public.editorial_comments(article_id,author_id,comment) values(article,auth.uid(),trim(note)); end if; insert into public.audit_logs(actor_id,action,target_type,target_id) values(auth.uid(),action_name,'article',article); return a; end $$;
create or replace function public.audit_privileged_changes() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ begin if tg_table_name='profiles' and new.role<>old.role then insert into public.audit_logs(actor_id,action,target_type,target_id,metadata) values(auth.uid(),'role_changed','profile',new.id,jsonb_build_object('from',old.role,'to',new.role)); elsif tg_table_name='articles' and new.reviewer_id is distinct from old.reviewer_id then insert into public.audit_logs(actor_id,action,target_type,target_id,metadata) values(auth.uid(),'reviewer_assigned','article',new.id,jsonb_build_object('reviewer_id',new.reviewer_id)); end if; return new; end $$;
create trigger profiles_role_audit after update of role on public.profiles for each row execute function public.audit_privileged_changes(); create trigger articles_reviewer_audit after update of reviewer_id on public.articles for each row execute function public.audit_privileged_changes();
