-- Phase 7: private patient-owned document vault. Uploaded binaries remain in Storage.
create type public.document_category as enum ('Patologi Anatomi','Laboratorium','Radiologi / Imaging','Surat Rujukan','Ringkasan Medis','Jadwal Terapi','Resep / Daftar Obat','Surat Kontrol','Discharge Summary','Hasil Konsultasi','Administrasi','Lainnya');
create type public.caregiver_status as enum ('pending','accepted','revoked');
create type public.document_permission_kind as enum ('view','download');
create table public.documents (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null check(length(title) between 1 and 160),category public.document_category not null,document_date date,journey_stage text check(journey_stage is null or journey_stage in ('diagnosis','biopsy','pathology','staging','treatment','monitoring','survivorship')),facility text check(length(facility)<=160),clinician text check(length(clinician)<=160),storage_path text not null unique,mime_type text not null check(mime_type in ('application/pdf','image/jpeg','image/png','image/webp')),file_size bigint not null check(file_size>0 and file_size<=10485760),file_hash text not null check(file_hash~'^[0-9a-f]{64}$'),original_filename text not null check(length(original_filename)<=255),notes text check(length(notes)<=4000),important boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint owned_storage_path check(storage_path like user_id::text||'/%'));
create table public.document_tags (document_id uuid not null references public.documents(id) on delete cascade,tag text not null check(tag=lower(trim(tag)) and length(tag) between 1 and 40),primary key(document_id,tag));
create table public.caregiver_relationships (id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references auth.users(id) on delete cascade,caregiver_user_id uuid not null references auth.users(id) on delete cascade,status public.caregiver_status not null default 'pending',created_at timestamptz not null default now(),unique(owner_user_id,caregiver_user_id),check(owner_user_id<>caregiver_user_id));
create table public.document_permissions (document_id uuid not null references public.documents(id) on delete cascade,grantee_user_id uuid not null references auth.users(id) on delete cascade,permission public.document_permission_kind not null,expires_at timestamptz,created_at timestamptz not null default now(),primary key(document_id,grantee_user_id,permission));
create table public.document_appointment_links (document_id uuid not null references public.documents(id) on delete cascade,appointment_id uuid not null,created_at timestamptz not null default now(),primary key(document_id,appointment_id));
create index documents_owner_date on public.documents(user_id,document_date desc); create index documents_hash on public.documents(user_id,file_hash,file_size);
alter table public.documents enable row level security; alter table public.document_tags enable row level security; alter table public.caregiver_relationships enable row level security; alter table public.document_permissions enable row level security; alter table public.document_appointment_links enable row level security;
create function public.can_access_document(document uuid,required public.document_permission_kind default 'view') returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from documents d where d.id=document and (d.user_id=auth.uid() or exists(select 1 from document_permissions p join caregiver_relationships r on r.owner_user_id=d.user_id and r.caregiver_user_id=p.grantee_user_id where p.document_id=d.id and p.grantee_user_id=auth.uid() and r.status='accepted' and (p.expires_at is null or p.expires_at>now()) and (p.permission='download' or required='view'))))$$;
create policy documents_owner_select on public.documents for select using(user_id=auth.uid() or public.can_access_document(id)); create policy documents_owner_insert on public.documents for insert with check(user_id=auth.uid()); create policy documents_owner_update on public.documents for update using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy documents_owner_delete on public.documents for delete using(user_id=auth.uid());
create policy tags_read on public.document_tags for select using(public.can_access_document(document_id)); create policy tags_owner_insert on public.document_tags for insert with check(exists(select 1 from documents d where d.id=document_id and d.user_id=auth.uid())); create policy tags_owner_delete on public.document_tags for delete using(exists(select 1 from documents d where d.id=document_id and d.user_id=auth.uid()));
create policy relationships_parties_read on public.caregiver_relationships for select using(auth.uid() in(owner_user_id,caregiver_user_id)); create policy relationships_owner_insert on public.caregiver_relationships for insert with check(owner_user_id=auth.uid()); create policy relationships_parties_update on public.caregiver_relationships for update using(auth.uid() in(owner_user_id,caregiver_user_id));
create policy permissions_owner_all on public.document_permissions for all using(exists(select 1 from documents d where d.id=document_id and d.user_id=auth.uid())) with check(exists(select 1 from documents d join caregiver_relationships r on r.owner_user_id=d.user_id where d.id=document_id and d.user_id=auth.uid() and r.caregiver_user_id=grantee_user_id and r.status='accepted')); create policy permissions_grantee_read on public.document_permissions for select using(grantee_user_id=auth.uid());
create policy links_owner_all on public.document_appointment_links for all using(exists(select 1 from documents d where d.id=document_id and d.user_id=auth.uid())) with check(exists(select 1 from documents d where d.id=document_id and d.user_id=auth.uid()));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('patient-documents','patient-documents',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy patient_documents_owner_insert on storage.objects for insert to authenticated with check(bucket_id='patient-documents' and (storage.foldername(name))[1]=auth.uid()::text); create policy patient_documents_owner_select on storage.objects for select to authenticated using(bucket_id='patient-documents' and ((storage.foldername(name))[1]=auth.uid()::text or exists(select 1 from public.documents d where d.storage_path=name and public.can_access_document(d.id)))); create policy patient_documents_owner_delete on storage.objects for delete to authenticated using(bucket_id='patient-documents' and (storage.foldername(name))[1]=auth.uid()::text);
create function public.touch_document() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$; create trigger documents_touch before update on public.documents for each row execute function public.touch_document();
-- Audit log details intentionally exclude titles, filenames, tags and medical notes.
alter table public.audit_logs drop constraint audit_logs_action_check; alter table public.audit_logs add constraint audit_logs_action_check check(action in ('article_created','article_updated','submitted_for_review','revision_requested','review_approved','article_published','article_archived','reviewer_assigned','role_changed','document_uploaded','document_downloaded','document_deleted','document_metadata_updated','document_shared','document_access_revoked'));
create function public.audit_document_change() returns trigger language plpgsql security definer set search_path=public as $$begin insert into audit_logs(actor_id,action,target_type,target_id,metadata) values(auth.uid(),case tg_op when 'INSERT' then 'document_uploaded' when 'UPDATE' then 'document_metadata_updated' else 'document_deleted' end,'document',coalesce(new.id,old.id),jsonb_build_object('mime_type',coalesce(new.mime_type,old.mime_type),'file_size',coalesce(new.file_size,old.file_size)));return coalesce(new,old);end$$; create trigger documents_audit after insert or update or delete on public.documents for each row execute function public.audit_document_change();
